### ISSUE TITLE
Sample issue

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#1]
This is what a GitHub issue looks like. You can use the "Labels" interface to the right to assign a label to your posting. For example, you can label your project proposal "project proposal".

**Comment by gabikeane** [comment]
In this course, we use GitHub issues in a few ways:
1. project collaboration
2. trouble-shooting homework problems
3. sharing interesting articles

You'll see your instructors on here pretty often, but we encourage you to help one another rather than relying on us to answer the questions ourselves.
