### ISSUE TITLE
Cataloging the Lovecraft Lexicon

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#10]
For my project proposal, I would like to suggest an analysis of the works of early-20th-century horror writer H.P. Lovecraft, who is most famous for creating the so-called "Cthulhu Mythos" shared universe, and comparing his works with other writers working in so-called "Lovecraftian Fiction." Lovecraft, while not a traditionally "good" writer, introduced many concepts and themes that have become core tropes of 20th and 21st century horror fiction, including the idea of unfathomable alien gods, monsters that are little more than malleable masses of teeth and hatred, and the "mysterious death cult." Those following in his legacy range from those merely adopting or modifying his themes (as with director and screenwriter John Carpenter and horror writer Thomas Ligotti) to those working directly in the Cthulhu Mythos, telling their own stories with characters and places created by Lovecraft (including authors Stephen King and Neil Gaiman).
 I intend to create a database of "Lovecraftian" terms and themes coming from his original works (including his novella _At the Mountains of Madness_ and his stories "The Shadow Over Innsmouth," "The Dunwich Horror," and "The Haunter in the Dark" by analyzing and marking up several of his stories. Using this database, I then plan to compare his works to those typically considered "Lovecraftian Horror," including but not limited to Stephen King's story "N.," the script of John Carpenter's _The Thing_, and even works of Lovecraft's own inspirations (such as Arthur Machen's _The Great God Pan_), in an attempt to either glean some sort of "Lovecraftian Rating" from the research or to define what, exactly, it means to be Lovecraftian Horror. My research questions would include: what terminology does Lovecraft most often use (aside from the obvious "eldritch," "squamous," and racial slurs), have any of Lovecraft's actual writing styles caught on in major Lovecraftian fiction, and, perhaps most importantly, do explicitly Lovecraftian works have anything to do with the man's actual writings beyond setting and namedrops? 
I have no clue who anyone else in this class is but feel free to contact me if this sounds like something in which you'd be interested! Those appreciating classic literature, horror, or just theme analysis would be preferred, but really as long as you're at least as good at coding as I am (and I am **not** good at coding) I'd love to have you on board!

**Comment by gabikeane** [comment]
[The Eldritch Project](http://eldritch.newtfire.org/) came out of Pitt-Greensburg's DH course last year.  I was lucky enough to speak on a panel with its creator, and it's an awesome project.  It's not unprecedented to continue work on an existing project from this course (or in this case, our sibling course), so don't let the existence of this project bum you out.  
If this is something you're interested in pursuing, we can try to get you in contact with the project owners.  You may need to shift your research question, but that's to be expected!

p.s. I added the flag to this myself, but please be sure you're adding labels when you need to.

**Comment by ebeshero** [comment]
@Idi0teque @gabikeane Greetings from Pitt-Greensburg! In fact, I've just been corresponding with the lead developer of the Eldritch project, Patrick Herron (@PPH3) and would be happy to put you in contact if you like. Patrick's work was, like yours, interested in tracing the **distinctiveness** of Lovecraftian language, and he and his team came up with an interesting linguistic analysis of semantic richness in the texts. I know he was interested in revisiting that markup, and perhaps the corpus work might be expanded...I'd encourage you to talk to him.

**Comment by Idi0teque** [comment]
Did not realize this was already done, lol! Still, it seems like the Eldritch Project is more focused directly on Lovecraft's writing, and not on Lovecraftian fiction; and if the Eldritch Project creators are alright with my usage, having an existing database of what makes Lovecraft distinctively Lovecraftian would be a massive stepping stone for this project/addition!

**Comment by djbpitt** [comment]
@Idi0teque Even where ideas converge, there's always something new to add, and one point of the public, open-license DH ethic is that developers are encouraged to build on the work of others. If you look in the upper right corner of the main page of the [Eldritch project](http://eldritch.newtfire.org/), you’ll see an image (gray and black, rectangular, begins with “CC”) that expresses a Creative Commons license, that is, the terms for reusing the content. This project has a CC BY (attribution) and NC (non-commercial) license. If you click on the image, it will take you to a page that explains what that means, but the short version is that you’re permitted to reuse the content in your own project.

**Comment by ebeshero** [comment]
@Idi0teque @djbpitt Yes, with attribution--meaning, please cite the source of the data (which you'd want to do anyway to explain what your methods and how you're building on the existing work). Additionally, I think @PPH3, a keen Lovecraft enthusiast, is likely to be very interested in seeing the work continue and eager to help.
