### ISSUE TITLE
Alice in Wonderland in Translation

### ISSUE THREAD

**Issue by enb34** [obdurodon/dh_course#13]
### Text
This project would focus on the work _Alice's Adventures in Wonderland_ by Lewis Carroll in two different languages, English and Japanese. 

 ### Approach
The analysis would first be conducted on an original version of _Alice's Adventures in Wonderland_ in English. The focus would be on noting the idioms, rhyme, puns, songs, and "nonsense" words of the work, as well as features of the text that may be difficult to analyze in direct translation. Analysis would then be conducted on the Japanese form of the text, _Fushigi no Kuni no Arisu_ (不思議の国のアリス), with concern to the same linguistic features.

### Research Questions
Works like _Alice's Adventures in Wonderland_ can be difficult to translate into other languages due to its use of rhyme, idioms, puns, and "nonsense" words. This project would explore how the Japanese translation of the text differs linguistically from its English counterpart, as well as how the translation was modified for its target audience.

**Comment by ebeshero** [comment]
@enb34 Greetings from an old Obdurodon-ian at the Greensburg campus, where I teach a "sibling" of this course.  I think this is a terrific proposal particularly for investigating English "nonsense" words to see how they might translate into Japanese. I wonder if the nonsense words are imported or how they are altered, and I wonder if you might be able to generate a typology of transformations that nonsense words underwent in the translation process! Another Obdurodon project, one of my favorites, studied [nonsense words in Dr. Seuss's books](http://seuss.obdurodon.org/index.xhtml) , and their methodology for identifying what counts as "nonsense" might be pertinent here. Take a look at their [Methodology page](http://seuss.obdurodon.org/index.xhtml).

**Comment by djbpitt** [comment]
@enb34 You might be interested in the [O’Henry project](http://o-henry.obdurodon.org/), which examined the use of honorifics in Korean translations of O’Henry. One unexpected discovery was that the Korean texts were not translated directly from the English; the route was from English through Japanese to Korean (the phonetics gave it away), and since both Japanese and Korean use honorifics, the Japanese mediation affected the meaning of the results.
