### ISSUE TITLE
Analysis of Critical Views of Reality in Soviet sci-fi

### ISSUE THREAD

**Issue by ianloughney** [obdurodon/dh_course#15]
This project would seek to investigate how Russian science fiction writers use the genre to critique the life and systems of the Soviet Union. The specific goal of this project would be to compare different means by which different writers achieve their critiques, and how they managed to get their works past censors during the time of their writing. For this project, I think the best approach to analyzing these texts would be to take smaller excerpts from larger works. This project could use Soviet novels, short stories, as well as films to explore how critiques are framed within science fiction. As far as texts to be used, there are a number of well known Soviet texts that I think would be best for a project like this given that research on them already exists to some extent. This would include novels like *We, Heart of a Dog,* or *Solaris.* In terms of film, I could look at *Teens in the Universe, The Andromeda Nebula,* or *Kin-Dza-Dza.* 

Possible contributors on this project would include richiebful or other classmates with knowledge  or Russian language or culture.

**Comment by JosephDRogers23** [comment]
Cool!
