### ISSUE TITLE
Kelly's Project Proposal

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#215]
**The State of Exception** 
        During the Weimar Republic period in Germany, Carl Schmitt wrote about dictatorships and what he termed the state of exception. Italian philosopher Giorgio Agamben expanded on Schmitt’s idea in Homo Sacer (1995) and State of Exception (2005). In the U.S. a state of exception occurred when the sovereign (executive and/or legislative branch) suspended juridical law after 9/11, creating two classes of people, those who are inside and those who are outside the law. Those who are outside are called “bare life,” meaning they have no rights under the law, and they can be killed without their death being considered murder (Guantanamo Bay detainees, Afghans, Iraqis, etc). The sovereign uses the protection of those who are inside (U.S. citizens) as a pretext to do whatever is necessary to eliminate the threat to them and the State. 
        After 9/11 the U.S. entered into the state of exception when President Bush used an executive order to start the war on terror. Juridical law was suspended when the Supreme Court sided with the Bush administration that the detainees at Guantanamo Bay had no right to habeas corpus (Rasul et al v Bush), meaning they could not be charged with a crime, given a lawyer, or a speedy trial all of which are rights guaranteed by the Bill of Rights. There are multiple other examples that we can discuss when we meet. The war on terror has been going on for 17 years with no end in sight. Under the guise of protecting the nation from terrorists the sovereign (the sovereign can change and still be called the sovereign for Agamben) is able to enact policies that go against our democratic values while increasing his or her power. 
       The research question for this project is: What executive and legislative actions were taken by our government and enacted by governmental agencies and the military support Agamben’s assertion that the U.S. suspended juridical power to enter into the state of exception and create “bare life” to ensure that the State stays in a perpetual state of exception?
This site would be useful to Agamben scholars who need the primary sources for their own research on the state of exception. Other possible users would be those interested in the war on terror and academic theories that provide another vantage point from which to understand or talk about the war.
        I have ideas on documents that could be included like Supreme Court cases, Bush’s executive order, Congress’ declaration, treaties about war crimes, etc. but I am know that there are many more out there that we could use to support my research question. I would also include the Constitution and perhaps use sections of the primary sources to show how it violates the Constitution. There are numerous ways we could handle the data, I have ideas, but group member’s input will be vital to make this site really interesting and useful to scholars of the war or Agamben.

**Comment by spkellyo** [comment]
**Agamben, the state of exception, and the U.S. "War on Terror"**

The research question for this project is: What documents can be used to show the executive and legislative actions taken by the U.S. government and enacted by governmental agencies and the military which support Giorgio Agamben’s assertion that the U.S. suspended juridical power to enter into the state of exception and to ensure that the State stays in a perpetual state of exception?

This site would be useful to Agamben scholars who need the primary sources for their own research on the state of exception. Other possible users would be those interested in the war on terror and academic theories that provide another vantage point from which to understand or talk about the war.

We would be using Giorgio Agamben’s conception of the state of exception to guide how we choose which documents to use on the site. I can provide the team with a short explanation of the state of exception and a few other terms he uses. Prior knowledge of Agamben is not necessary, its fairly straight forward. The documents we would gather would be things like Supreme Court cases, Congress’ resolution for the use of force (not war) to apprehend the perpetrators of 9/11, public documents about what happened at Abu Graib, waterboarding, etc. They could be cross referenced with the Constitution to show how this is not a legal war and how the U.S. has compromised its democratic values through the actions taken by the sovereign (Agamben's term for the leader of a State). The main idea in the state of exception is that the sovereign uses the protection of American lives as justification for the illegal detainment of human beings who have been tortured, the bombing of villages killing tens of thousands of innocent people in Afghanistan and Iraq, and denying these people their rights under U.S. law (detainees) and international laws and treaties (human rights).

**Comment by pickettj** [comment]
Cool project. Plus pretty soon you might have a "national emergency" to work with, so very timely...
