### ISSUE TITLE
Rebekah's Project Proposal

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#221]
Potential Research Question: How are males and females viewed differently in Arabic literature, and does this depend on any other factors such as age, social status, etc...?

Arabic literature is famous for its use of frequent and repetitive adjectives. These adjectives are used in order to convey a heavier emphasis than what our culture as Americans are used to. Along with these adjectives are certain sex and gender stereotypes that are frequently conveyed and perpetuated via said adjectives and topics that usually end up being tied to being classified under either the "male" or "female" umbrella. 

I am a Linguistics major with an Arabic certificate and a decent amount of experience with Arabic Literature, so a project like this would definitely be something relevant to my collegiate studies. 

In this hypothetical project, I would like to sit down with a few teachers from the Arabic Department at Pitt and carefully choose 4-6 different stories to analyze. While doing the analysis of the texts, I could see myself possibly looking at tagging instances of stereotypical phrases, as well as the different adjectives or adjectival phrases and which gender they are associated with. 

This would be beneficial for researches to view because of its potential to be used in arguments for other research on topics such as social issues, gender theory, feminist theory, and so on. It will also just be interesting to look more in depth and more critically at how language is being used to mark genders as being different from each other in the Arab world.

A definite drawback that I could see causing an issue during this project is the issue of Arabic being read and written right to left, which has already caused me a few issues within XML. This will be something that I will have to be cognizant of when doing mark up of the texts to ensure that there are no errors or formatting issues. 

Potential collaborator is possibly Kasey Busko.

**Comment by djbpitt** [comment]
Closed because new proposal was submitted as a replacement.
