### ISSUE TITLE
Kasey's Project Proposal

### ISSUE THREAD

**Issue by k-busko** [obdurodon/dh_course#222]
**Use of language in Tolkien's works in regards to the themes of nature and the environment**

Project Overview:
- Use of texts by J.R.R. Tolkien (LOTR, The Hobbit)
Analysis of language patterns in the texts used to describe nature and the environment
 - Examination of the ways language is used about these themes depending on which characters are speaking

For my project I would like to conduct document analysis from passages in J.R.R. Tolkien's works that include language about nature and natural environments. In addition to this, I would also be categorizing which characters share language patterns when discussing these topics throughout the books' dialogue.

Known for being one of the most famous authors in the fantasy genre, J.R.R. Tolkien was also known for his intense belief in and practice of environmentalism. He showed this through his frequent inclusion of environmental descriptions in his books. He also used his characters to not only describe the environments they found themselves in but also provide multiple and varying perceptions of nature. This was dependent on a given character’s culture and how that culture interacted with the natural environment. A hobbit would speak differently of a forest than an orc.

In conducting my project I will take passages from both The Hobbit and the Lord of the Rings trilogy in order to create an archive that depicts examples of dialogue from different backgrounds (i.e. hobbits, elves, dwarves, orcs, men). Passages will be narrowed down to specific instances of language that pertain to or revolve around the natural environment. These will then be evaluated on the quantity of positive versus negative descriptors and then compared against the other characters. 

Research questions that could be used to guide this assignment include:

To what degree do protagonists use positive language about the natural environment and antagonists use negative language? And vice versa?

Is positive/negative language used by characters directly about the environment or how the environment is treated by other characters?

Potential collaborators for this project include Rebekah Fox.

**Comment by gabikeane** [comment]
Unfortunately, Tolkien's work is still under copyright. *The Hobbit* was first published in the 1930s, so even without the Tolkien estate's intervention, it would be ineligible for use in this course.

If you'd like to pursue a similar project with a novel outside of copyright, please feel free to comment on your existing proposal with something new.

**Comment by k-busko** [comment]
I still want to do a language comparison between characters regarding a theme so I am going to swap out Tolkien's works and the theme of nature/the environment in favor of H.G. Wells' _War of the Worlds__ and the attitudes reflected in their use of language about the Other. I will compile a list of characters and their respective dialogue and put that information on a spectrum ranging from positive to negative language that centers on the Other (in this case the Martians). Potential research questions could include: 

- What factors about a character and their background predict the probability of their use of positive or negative language concerning the Other?

> Are there language patterns between characters who share the same or similar ideas regarding the Other?

**Comment by gabikeane** [comment]
This sounds like a perfect substitution! Thanks for being so flexible!

**Comment by djbpitt** [comment]
Great substitution! We can confirm the public domain status of Wells’s work at <https://www.napier.ac.uk/about-us/news/hg-wells-books-enter-the-public-domain>.
