### ISSUE TITLE
Ethan's Project Proposal

### ISSUE THREAD

**Issue by Ethandaniel47** [obdurodon/dh_course#226]
# UNEARTHING POE 
# Exploring Edgar Allan Poe's Relationship with Confinement and Release
Edgar Allan Poe, born January 19th, 1809, is said by some to be the father of what we know recognize as the genre of Detective Fiction. For me, he has served as a wealth of the dark and the macabre and his creepy tales never fail to make my skin crawl. Poe also draws forth images, for me, of entrapment and entombment. So often in Poe's stories we encounter characters who are trapped in solitary rooms, trapped mentally in the metaphysical problems of life and emotion. Sometimes these characters are literally entombed: in sepulchers by the sea, in wooden tombs, bricked up behind walls or beneath floorboards. For me, at least, this has been the crux of Poe's poetry and his prose. But how often is this actually the case? How often does a literal form of entrapment take place within a given tale or poem? How many times is this entrapment physical versus mental or emotional? How often do the contained things get out? Does anything, with Poe, truly stay buried in the darkness for which he is so known, or does all, despite all efforts, come at last to light? Through verb and noun analysis of Poe's poetry (as well as some of his shorter prose) I hope to locate words that denote these closed or confined spaces or feelings, be they physical or emotional, and to compare those findings with those that denote openness, release, and escape. In doing so I hope to draw a research conclusion as to whether Poe's fiction should remain a dark, pessimistic corpus, or to see if we ought to, perhaps, reconsider Poe as a writer who finds light in the darkness, and believes, even in the dankest or prisons, in the hope of eventual escape.

**Comment by ddaud02** [comment]
I find this project very interesting. I am taking a Gothic literature class, and my knowledge of the gothic was largely about architecture, not literature. It is a very comprehensive topic because we are not only studying medieval texts but also modern texts such as the short novel "Los chicos que vuelven" (The boys who come back) by the Argentine writer Mariana Enríquez. This novel has both gothic and detective elements.
