### ISSUE TITLE
Emma's Proposal: Gender Based Analysis of Yugoslav Folklore 

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#228]
Emma Mamula

Folklore is an essential component that helps to shape the identity of a countries and their cultures. Countries of the former Yugoslavia have a rich and extensive history of folk music and poetry, some of which is featured in _An Anthology of Jugoslav Poetry_ by Dr. B Stevenson Stanoyevich. This text analyzes the deeper religious, nationalistic, and emotional connotations of the poetry. This look into the realm of folklore is important because it acknowledges its relevance in the cultural shaping of the country.

In this project I aim to research the gender aspects of traditional Yugoslav folk music and poetry. I will use XML to mark up the pronouns and nouns, that are typically perceived as masculine or feminine in the lyrics and prose. Since Yugoslav culture tends to be patriarchal, I am interested in seeing whether or not women are more frequently described in the literature, or simply just described and how that is representative of the traditional culture as a whole. I think using folk songs and poetry is useful because not only is it still popular in the countries of the former Yugoslavia, but it is also especially popular amongst the diaspora in the United States. The longevity of the literature speaks to its greater impact.

The findings from this research would be useful for interdisciplinary studies, such as Gender Studies, Slavic Studies, and Cultural Studies. It could also be used to develop into a broader study of the effects of nationally based music in Eastern Europe and how it can potentially provide social support for the continuation of patriarchal societies and traditional ideals. It will also help to shed light on how it is necessary to change how we interpret products of culture as we progress, but we must also be sure to not downplay its repercussions. This research could develop into a more sociological based study.

Possible collaborator: Mitchell Luckman

**Comment by ebeshero** [comment]
This sounds like it could be a terrific gender and folklore investigation. How would you find base texts to mark up? You mention what appears to be a print anthology of Yugoslav poetry, but is there any material already available to start with on the web so you're not having to transcribe material as you get started on the project?
