### ISSUE TITLE
James' alternate proposals: Persian gazetteer or Zoroastrian quasi-translations

### ISSUE THREAD

**Issue by pickettj** [obdurodon/dh_course#232]
The [first proposal I wrote](https://github.com/obdurodon/dh_course/issues/219) depends on finding someone else who can read Hebrew, which may not be possible. So I wanted to briefly mention two other projects I have in mind.

(1) **Multiple versions of a Zoroastrian text**: This project would explore how a Zoroastrian text written in [Middle Persian](https://en.wikipedia.org/wiki/Middle_Persian) (aka Pahlavi, written in modified Aramaic script) changed when "translated" into New Persian (written in Arabic script). Since both "languages" are Persian, some terms were simply transliterated into the new script; and others were mapped onto approximate Islamic concepts. XML markup would track the links between key terms and symbols across the different versions of the text to see how much the religious worldview changed in the transition.

(2) **Geo-mapping a Persian gazetteer**: This project would essentially mark up a 1911 Persian language gazetteer of Bukhara (now in Uzbekistan) to correspond to different geographic locations. How many words are devoted to each section (for instance) could tell us something about the relative political /cultural importance of different locations in the emirate.

**Comment by ddaud02** [comment]
I find your proposal very interesting, studying texts produced by an X culture, and translating them into several languages can say a lot about the cultures that receive those texts. For example, what interpretation, of the bibles or religious texts of each culture, is absorbed and which elements are discarded. This seems very interesting to me personally.
