### ISSUE TITLE
Project Repo: Persian Gazetteer

### ISSUE THREAD

**Issue by pickettj** [obdurodon/dh_course#242]
[Link to Persian Gazetteer project repo](https://github.com/pickettj/central_asia_gazetteer).

Team: James & [Jon](@engeljonathan98)

### Description

In 1910 (1328 h.) a Central Asian scholar named Muḥammad Ṣādiq Qarāwul Bīgī Gulshanī Bukhārī ("Gulshani" for short) wrote a geographical treatise about his native country of Bukhara. At that time, Bukhara was a semi-autonomous protectorate of the Russian Empire, and its territory is now split between Uzbekistan and Tajikistan. Gulshani's text (which has never been translated) details the cultural, economic, and political landscape of Bukhara.

Using a combination of XML markup and geo-spatial mapping software (QGIS), this project will use this text to gain a sense of the world of Bukhara from Gulshani's vantage point. What locations were imagined to be the most culturally significant? How do the locales most important to Gulshani relate to population centers today? Can we get a sense of what was "foreign" and distant from Bukhara?

**Comment by spkellyo** [comment]
I love this project idea! I am very interested in the geo-spatial mapping software that you mention, but I understand you have a lot of experience with building sites and the learning curve may be too steep for us to use this in our Sherlock project. I will certainly try it out. Do you have to buy the software or can you get it through Pitt? Is there a tutorial you recommend for trying this out? We learned how to add a map on Wednesday, but this seems different. Does it use Java? I might have to put this on my summer study list, but any insights into would be great. I don't mean explain it, just an idea of where to go to get started. I look forward to seeing your final project! Good luck.
