### ISSUE TITLE
TEI headers -- a clarification

### ISSUE THREAD

**Issue by zme1** [obdurodon/dh_course#243]
Good afternoon, everyone. I wanted to correct an error I made during today's lecture on compiling our `teiHeader`, specifically where you document your source(s). 

My mistake in today's lesson regarded what kind of information went inside the `titleStmt` element, directly inside `fileDesc`. I *erroneously* marked up the file so as to attribute the author of our **document**, i.e., Thomas Jefferson, inside the `titleStmt` for our file. In Real Life, however, the `titleStmt` element is reserved to document contributors (authors, editors, etc.) **for the file itself**. In other words, the `titleStmt` reflects the contributions of the individuals who actually wrote the file -- you! As the author of your TEI file, you all should attribute yourselves for the work you've done in including yourselves in your `teiHeader`, inside the `titleStmt`.

As for the actual primary source and its authors, editors, etc., that information will be located in the `sourceDesc` element, which provides different options for you to cite the actual source, its authors, etc. with a handful of different bibliographic elements, and `biblFull` would probably work best here. As you'll see in `biblFull`, you can fully document your source's contributors, publishers or distributors, and the source's availability. 

If you run into any problems this weekend with compiling your headers, instructors will be watching our Issues Board, as always! Otherwise, we'll see you all on Monday.

**Comment by djbpitt** [comment]
Thanks for the clarification, Zac! 

One way to think about this is that the `<fileDesc>` (which contains the `<titleStmt>`) is a description of the TEI file you are editing. The `<sourceDesc>` is a description of the source you used to create your TEI document, such as a document available on the National Archives web site.
