### ISSUE TITLE
Interaction between HTML and XML

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#245]
If we want to apply HTML to one of the exercises we did in XML, is there a way to convert the XML to a working HTML document or to paste the XML into the HTML? 
I tried changing the extension and it produced a page that opened in chrome as a webpage but didn't have the HTML header.
When I tried to paste the XML document into the HTML document it said the root element subverted schema expectations and every time I deleted an element it said the same thing about the next element.

Looking further it looks more like the xml document gets associated and not embedded and HTML is done with clean text. Is that the case?

**Comment by gabikeane** [comment]
This is something we'll learn to do when we learn XSLT (eXtensible Stylesheet Language Transformations) later on in the semester. 

For now, though, it's gonna involve a lot of pasting and manually changing semantic tags to presentational ones.

**Comment by sjw82** [comment]
Is it something we need to do for this assignment?

**Comment by gabikeane** [comment]
Nope! You're free to make the content whatever you'd like. Your cat, a favorite food, your roommate. If you'd like to take this opportunity to mess around with presentation on a text of your choosing, you can do so. But XSLT is going to make that a lot easier later on, so don't feel like you have to make something related to previous XML now if you don't want to.

**Comment by zme1** [comment]
[w3schools](https://www.w3schools.com/tags/) has a helpful resource that documents the moderately small HTML tag inventory. This is a site that we revisit periodically throughout the semester; it's an easy and often direct way to find answers related to web development. Although the tutorials are hardly thorough, they are great introductory tools for new developers.
