### ISSUE TITLE
Discussion Post: Command Line and Github

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#246]
I initially struggled to create a local connection with Git. Now I can say that I understand its purpose and terminology, but can’t claim to be capable with its application. Yesterday I had to push some code to Github and I had the same issues as my first time using the command line, having difficulty with restarting from the beginning rather than from the previous step when things would become fatal. I would like to get more practice with command line; inexperience is the main problem as the primary obstacle is the interface.
Github was easier to pick up; the interface is more intuitive. I like Github a lot, particularly the issues and projects. The project tab is useful because it allows the user to visualize procedures and progress. Also being able to have different project boards allows for more concentration; for example in our project we might end up with a project board dedicated solely to the different verses, each card corresponding to an issue with a checklist of steps of analysis to be done for the verse. Being able to tailor the columns also allows more specificity; for example I have a board that says: to-do, in progress, requires mentor attention, done. I didn’t like having things in-progress that I could no longer work on, but the project board accommodates that. And since each card can be an issue, it is easy for the mentor to then go on and respond thoroughly, not being limited to a little project card.
Issues similarly allow for complexity as they’re essentially blog posts but for this reason also contribute transparency to the project. The viewer as well as the participants in the project can see the logic behind each step as it is explained in prose and not limited to a task on a to-do list. Particularly the assignee option on issues is valuable because it allows clarity in who is responsible for what and notifies the person that it has become their task, improving team efficacy.

**Comment by zme1** [comment]
@sjw82 Thank you for the quick response to our Single Issue discussion! We were a bit late in posting the "single Issue", but now that it's up, would you mind relocating your response to the new Issue?
