### ISSUE TITLE
Inserting text into XML

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#252]
How would we insert a quote into xml? For example if you line says:
`<quotes>Many women have done well <ref>Proverbs 31:29</ref>: Adam, the first man, was commanded about six commandments.</quotes>`
And I want to insert the text of Proverbs 31:29 into the XML so that it would be searchable later, how would I go about that?

**Comment by zme1** [comment]
@sjw82 One method could simply comprise nesting your elements a bit differently to associate the book, chapter, and title to the actual text of the verse. That way, if you wanted to find the location of any verses that contain the name 'Adam', for example, you could do so (with XPath, which we'll be learning soon). If I've understood your question correctly, here's what I would consider doing:

```
<q>Many women have done well <ref><loc>Proverbs 31:29</loc>: <text>Adam, the first man, was commanded about six commandments.</text></ref></q>
```

This way, your entire passage is wrapped in a `ref` element, and it has `loc` and `text` children, the former containing the location of the passage in the Bible, and the latter containing the text itself. Is this something along the lines of what you were looking for?

**Comment by sjw82** [comment]
@zme1 Sorry, this example was super unclear. I want to insert the text of proverbs 31:29 which is "Many women do noble things, but you surpass them all.” into the quote from the text we're analyzing which is "Many women have done well (Proverbs 31:29): Adam, the first man, was commanded about six commandments."
My guess had been that it would be:
`<quotes>Many women have done well <ref bibtext="Many women do noble things, but you surpass them all.">Proverbs 31:29</ref>: Adam, the first man, was commanded about six commandments.</quotes>`

**Comment by zme1** [comment]
@sjw82 Ah, I see. One alternative method you could try is embedding your inserted text within a `note` or equivalent element to distinguish it from the original text itself, while still giving yourself the freedom to retrieve or process it. It could look something like this:

```
<quotes>Many women have done well <ref>Proverbs 31:29<note type="verse">Many women do noble things, but you surpass them all.</note></ref>: 
Adam, the first man, was commanded about six commandments.</quotes>
```

There could be more sensible or effective methods to approach this that depend on your preferences and ultimate goals for this encoding, but hopefully this will get you started! Is this of any more help?

**Comment by djbpitt** [comment]
@sjw82 The version that includes the quoted biblical text as an attribute value is risky. I'll reproduce it here first:

```xml
<quotes>Many women have done well <ref bibtext="Many women do noble things, but you surpass them all.">Proverbs 31:29</ref>: Adam, the first man, was commanded about six commandments.</quotes>
```

The risk is that attribute values cannot contain markup. That isn’t an issue here because your biblical quotation doesn’t contain markup, but what if you had a quote where you needed to tag some of the words? If that’s a concern, using a child element would be better.

How about something like the following:

```xml
<quotes>
    <paraphrase>
        <cite>Many women have done well</cite>
        <source book="Proverbs" chapter="31" verse="29">Many women do noble things, but you
                surpass them all.</source>
    </paraphrase>: Adam, the first man, was commanded about six commandments.
</quotes>
```
