### ISSUE TITLE
Regex for 'any number'

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#254]
Is there a regex for "any number"? For example, we can use the following for "any text":
firstname = attribute firstname { text }

But what if, instead of any text, I want to allow only numbers?
I tried this but got errors: year = attribute year { [0-9]* }

I have also used '[0-9]*' (with quotation marks), \^[0-9]*\, etc. and still getting errors...

**Comment by ebeshero** [comment]
For regular expressions, there is `\d` or `[0-9]` to represent digits. However(!) in Relax-NG schema usage as you are indicating here, you want to address numbers as a datatype--which are made out of regular expression patterns. These are ready made for data like what you're trying address here. You seem to be creating a rule for a year attribute, presumably to hold a four-digit year, right? Read about the date datatypes, and this may give you some good ideas of options for patterning not just integers but time data. There are [International standard (ISO)](https://www.iso.org/iso-8601-date-and-time-format.html) patterns for encoding dates:

* `xsd:date`: formatted as yyyy-mm-dd (four-digit year, followed by two-digit month, and two-digit day)
* `xsd:gYear`: for just the four-digit year
* `xsd:gYearMonth`: When you are referring to a month and year, without a day

There are other combinations, each with a distinct datatype you can reference. Take a look at http://dh.newtfire.org/explainRNG.html#datatypes for some examples of how to code these as options in a Relax NG Schema, and at a complete list of datatypes for use in XML schemas here: http://books.xmlschemata.org/relaxng/relax-CHP-19.html

**Comment by ddaud02** [comment]
Thanks! Very helpful to know about datatypes and have a list and a review. Will add to the assignment.
