### ISSUE TITLE
TEI Guidelines backup site

### ISSUE THREAD

**Issue by ebeshero** [obdurodon/dh_course#255]
A few of you (current and past students) may be working with the TEI just now--and you may have noticed that the main Guidelines site (http://www.tei-c.org/guidelines/p5/)  is down. Here's where to access a backup of the current Guidelines:
https://jenkins.tei-c.org/job/TEIP5/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/index.html

**Comment by zme1** [comment]
@ebeshero I thought I was crazy....

**Comment by ebeshero** [comment]
@zme1 Nope. The website editor sent a message on the TEI listserv on Friday about the site being down for “maintenance”, but I didn’t expect that meant for multiple days...but I am sure it’ll be back soon.

**Comment by djbpitt** [comment]
A new backup TEI server was just announced this morning:

>The TEI-C servers are currently offline as a result of an unplanned downtime of the ADHO servers.
While our servers are being restored, a temporary copy of the TEI-C site can be accessed at:
<https://tei-c.dhinstitute.ca>.
