### ISSUE TITLE
Recording Attribute Tags in RNC

### ISSUE THREAD

**Issue by Ethandaniel47** [obdurodon/dh_course#256]
I have been struggling pretty consistently on the exam with understand how to validate my schema against a document wherein the meta data (author, title, date, stanza number) are included as attributes instead of separate elements containing text. Tagging attributes in a way that is valid both for the RNC and XML has been a fruitless struggle for the last two hours despite referring to several online guides and class notes. Any suggestions?

**Comment by djbpitt** [comment]
@Ethandaniel47 Attributes can be included in Relax NG content models the same way that elements are; see, for example, our treatment of the `speaker` attribute at the bottom of our <http://dh.obdurodon.org/relaxng.html>. It sounds, though, as if the issue you’re running into may be not that you have attributes, but that you have *only* attributes, and the element content is empty. Relax NG has an `empty` keyword for modeling empty content. See the discussion of empty elements at our <http://dh.obdurodon.org/relaxng2.html>.
