### ISSUE TITLE
GitHub browsing add-on for Chrome and Firefox

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#259]
The <https://github.com/ovity/octotree/> browser add-on for Chrome and Firefox (scroll down for installation instructions; also for Safari, but the installation is trickier) adds a hierarchical menu to your browser window when you connect to GitHub. This may be convenient as your project grows and you add subdirectories to your repo.

**Comment by ddaud02** [comment]
I just install it, not sure how it works.
