### ISSUE TITLE
Issue adding image in HTML

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#260]
I've been following all of the proper steps from the w3schools website to insert an image but my HTML document keeps coming up as not well formed....Checked a few other websites and couldn't find any solutions to this issue. Not sure where to go from here?

**Comment by zme1** [comment]
@rmf96 Would you mind posting a snippet of code so that we could see what you're working with?

**Comment by rmf96** [comment]
Disregard. Ducky to the rescue.
