### ISSUE TITLE
Test #3: Regex

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#262]
Hi guys, where can I find **Test 3: Regex** ?
<img width="1259" alt="screen shot 2019-02-16 at 9 52 25 am" src="https://user-images.githubusercontent.com/46380238/52901394-eb2c0500-31d0-11e9-855f-0e7786cc2f6d.png">
Last time I spend the whole weekend figuring out how to do this test.

**Comment by djbpitt** [comment]
Sorry! Going up right now ...

**Comment by djbpitt** [comment]
It's up at <http://dh.obdurodon.org/2194_regex-test-instructions.xhtml>. Since the delay was our (well, my) fault, we’re resetting the deadline (originally Monday, February 18 before class) to Wednesday, February 20 before class.

**Comment by ddaud02** [comment]
![thumbs-up](https://user-images.githubusercontent.com/46380238/52902072-a5c00580-31d9-11e9-996e-d6cc141640a1.jpg)
