### ISSUE TITLE
 The XPath browser window in <oXygen/>

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#263]
HI, I'm trying to figure out what's the XPath browser window in OXygen, we did something in class, I remember that we pick Xpath 3.0, but I do not remember how and where this is found. Could anyone help me? Thanks.

**Comment by zme1** [comment]
@ddaud02 When you tried to write &lt;oXygen/&gt;, the markdown styler parsed your literal brackets as code. Just as we do in XML, when we want to write literal angle brackets, we need to use their XML entity strings. These are `&lt;` for a left-angle bracket and `&gt;` for a right-angle bracket.

In your &lt;oXygen/&gt; window, see the "XPath 2.0" dropdown label to the left of your browser window. Click that, and select "XPath 3.0". Let us know if this helps!

**Comment by ddaud02** [comment]
Thanks, I still can not see that **menu**, by the way, I'm using a **Mac**.

**Comment by ddaud02** [comment]
Found it! Thanks.

**Comment by zme1** [comment]
That's okay; &lt;oXygen/&gt;'s interface is the same across operating systems. The dropdown menu (where you update your version of XPath) is directly next to the browser window (where you execute the XPath searches). They both appear just below the toolbar which extends across the top of your screen. The browser window has "Execute XPath on 'Current File'" written inside it, and the dropdown should initially have "XPath 2.0" written inside it.
