### ISSUE TITLE
Due date regex test

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#265]
Syllabus assigned it Friday, which usually means due by next class. The courseweb says it's due on Wednesday. When is the due date for this assignment?

**Comment by zme1** [comment]
@MLuckman Since we did not publish it until Friday evening, we extended the deadline to Wednesday before class.

**Comment by MLuckman** [comment]
@zme1 thank you!

**Comment by djbpitt** [comment]
@MLuckman Oops! Not only was I late posting the test, but when I thought I was spamming you all through CourseWeb Saturday morning to announce the extended deadline, I spammed the wrong class, which I discovered only now, when I went to check after reading your posting. What @zme1 writes above is correct, and both the lateness and the misdirected announcement of the extension are my fault. Very sorry!
