### ISSUE TITLE
Markdownpad 2

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#267]
**Markdownpad**

In a previous class we also did a lot of markdown, and this program is pretty useful once you start typing up longer things like your responses. It's free to use and I think it's pretty useful especially
[when you're making links.](http://markdownpad.com/download.html) It has a similar function to the preview tab in GitHub, because it shows you what the markdown will render as and can help you get used to markdown syntax.

**Comment by djbpitt** [comment]
Thanks, Mitchell. That one is for Windows; a good equivalent on Mac is [Macdown](
https://macdown.uranusjr.com/).

**Comment by Nerdologist** [comment]
@MLuckman Do you think the Markdownpad program is somehow superior to the Oxygen editor when it comes to writing markdown files? If so, how is it superior? I see the utility of the features you mention, but it is unclear to me that they make Markdownpad superior to Oxygen.

**Comment by MLuckman** [comment]
It is, I think. In Oxygen, you have a choice between the weird mixed view - bolded but not larger headings, red-colored code - and the "presentation" view that does display everything fine.

Markdownpad is a little clearer, because there is a completely unchanged view - nothing looks different, it is just notation - and then a prettier presentation view that I think is worth the download just so the code sections look nicer.

If you're satisfied with the oxygen interface, the ease of use for Markdownpad might not be worth the download but if you don't love oxygen then check it out.

**Comment by pickettj** [comment]
FWIW, I take all of my notes for everything in Markdown via various different software. For instance, I love [Ulysses](https://ulysses.app/) (Mac only, and paid, unfortunately) as a kind of OneNote replacement; and [nvALT](http://brettterpstra.com/projects/nvalt/) (Mac only, free) to create a kind of searchable database of my notes. (Neither is a replacement for Oxygen, however.)
