### ISSUE TITLE
XPath Expressions - Class Discussion Post 02/20

### ISSUE THREAD

**Issue by khuber116** [obdurodon/dh_course#268]
While working on the first XPath assignment (and looking for any resources that could help me figure out what was going on) I stumbled upon [this](https://devhints.io/xpath) list of expressions. It didn't give me a direct answer, but it did help me figure out what I needed to enter to return the desired results. It also gave me a better idea of what XPath can do along different axes, so I thought I would pass it along in case anyone else might find it useful.

**Comment by k-busko** [comment]
In the second XPath homework, it took me a while to figure out how to answer one of the questions asking you to include two elements to exclude in your XPath search (<l> and <ab>). I ended up putting 'or' between the two wrapped in parentheses and square brackets and it worked. I was just wondering if there is an alternate way to search for multiple elements present or not present or if anyone found their answer from a totally different XPath.

**Comment by brenda275** [comment]
@k-busko Instead of using 'or' I know I used 'and' because I interpreted the question as excluding both elements opposed to excluding either one or the other. Therefore, I know instead of using 'and' and wrapping it in a single pair of square brackets you can also just write another sequential predicate and have two pairs of square brackets (one for each predicate).

**Comment by Guifindor** [comment]
Thank you for posting this resource! I may be using this in the future, though I imagine I'll still be googling things when things go wrong. As for @k-busko, as far as I know, you have to specify each element you're looking or not looking for in XPath separated by boolean logic operators. I've tried googling your question while waiting on another program for another class to finish running, but have not found any new methods. That is all I know on the matter that I can confidently say at the moment.

**Comment by ddaud02** [comment]
I'm glad that you posted this, it is really helpful. I spend many hours reading the instructions on our main page and tried some codes that I thought that was going to help me but I failed many times. This list puts together a lot of codes that may be helpful to figure out something, thanks.

**Comment by djbpitt** [comment]
@khuber116 Thanks, Kyle! I’ve added a link to the XPath cheat sheet at <https://devhints.io/xpath> to the XPath section of our main course page.
