### ISSUE TITLE
Regular Expressions Resource: Class Discussion Post 

### ISSUE THREAD

**Issue by AncientGreekGeek** [obdurodon/dh_course#269]
While working on the RegX homework and tests I found that this sheet really useful! It is similar to what we have been provided but a little bit more concise. I really like how it condenses all of the basic symbols and their meanings onto one page and overall I used this sheet a lot: http://web.mit.edu/hackl/www/lab/turkshop/slides/regex-cheatsheet.pdf

**Comment by loreese** [comment]
This is great--I struggled a lot more with the regex than I thought I would and realized I need to seriously brush up. Will definitely be referring to this as a quick ref in the future!

**Comment by ddaud02** [comment]
Thanks for sharing, it is a lot to remember, personally, I struggle with connecting the dots, this technology is like playing chess, even though you are writing codes to do something specific, you have to think 10 moves ahead.

**Comment by djbpitt** [comment]
@AncientGreekGeek Thanks, Thyra! I’ve added a link to the cheat sheet in the regex section of our main course page.
