### ISSUE TITLE
XPath Videos on Youtube

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#271]
This introductory video [https://youtu.be/1g52OAyD3UI](url) that I found on **Youtube** is very interesting because you can see concrete examples (9). I personally prefer this type of media because not only can I repeat it several times but also I can pause it and repeat the steps that are explained in the video. Classes are important, but by themselves, they are not enough to retain all the information received.

**Comment by djbpitt** [comment]
Thanks, @ddaud02! The link above is _printed_ correctly, but it doesn’t go where it should on click. You can copy and paste it, or click on <https://youtu.be/1g52OAyD3UI>.
