### ISSUE TITLE
Terminal-Git-GitHub

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#272]
Hi, I'm trying to learn how to use Terminal, I'm finally at the last part when you have to press (**i**) to write the note. Does anyone know what's next? enter/command does not work or "do the job". 
<img width="847" alt="screen shot 2019-02-21 at 7 29 20 pm" src="https://user-images.githubusercontent.com/46380238/53211409-0c488780-360f-11e9-9829-5f199bc12729.png">

**Comment by gabikeane** [comment]
You've gotten yourself into the fearsome Vim text editor! Use the Escape (Esc) key to move to normal mode in Vim, then type `q!` and hit enter.

To avoid this again, when you type your commit command, use the -m switch, like this:

```git commit -m "my commit message here"```

**Comment by ddaud02** [comment]
Thanks, @gabikeane, it worked :)
![zoom_double_751199](https://user-images.githubusercontent.com/46380238/53212240-3cddf080-3612-11e9-8b5e-094a67651a74.jpg)

**Comment by djbpitt** [comment]
Git defaults to using *vim*, which is very unfriendly to new users. It isn’t unlearnable, but learning to use vim probably isn’t the best use of your time right now. 

The best way to set a Git commit message is at the command line, as Gabi describes, above. But you can also configure Git on your machine to use a different editor than vim by default, as explained at <http://web.mit.edu/6.005/www/sp14/tutorial/git/config.html>. You’ll need to decide which editor to use, and you’ll need to be able to specify a command that launches it. Nano, described at the preceding link, is popular; if you want to specify something like BBedit (mac) or Notepad (Windows), you’ll need to Google for how to do that. And if you do, post the link or the answer here!
