### ISSUE TITLE
Xpath Exercise Number 3

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#273]
Hi guys. does anyone know what is (Kay 733-34) ?It is mentioned many times. (Kay 749-50)(Kay 628-31)and (Kay 741-43, 877-79).
<img width="1018" alt="screen shot 2019-02-21 at 9 27 18 pm" src="https://user-images.githubusercontent.com/46380238/53215656-94cf2400-361f-11e9-973c-f462898a5b08.png">

**Comment by gabikeane** [comment]
That's a reference to the text book. Check the course description!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ddaud02** [comment]
Thanks, I just download the pdf.
