### ISSUE TITLE
String-length operation issue

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#274]
The xpath `//sp/string-length(.)` pulls up the error message "XPath failed due to: The context item for axis step root/descendant::sp is absent" when I enter it. In this case, I'm not sure what descendant would be referred to. What's going wrong?

**Comment by zme1** [comment]
@sjw82 When I plugged your XPath expression into my own XPath browser, it returned the results I expected. Are you sure that this is the expression you used, and that you launched the XPath search inside the XML file?
