### ISSUE TITLE
XML put my file in markup but saved as .xml

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#277]
I marked up a sample file and then I pushed it to our repo with a unique file name. For some reason, it started giving me crazy errors when I started writing the schema. So, I decided to just close Oxygen down and then open it back up. Now it looks like this: 
[xml problem.docx](https://github.com/obdurodon/dh_course/files/2902096/xml.problem.docx)
If you can't view this please post in comments and I will figure something else out, it didn't like the screen shot. I can't copy and paste either. Luckily this was just a sample, but it took a while and I'd like it back. I'm not sure how to fix this. Thanks!

**Comment by djbpitt** [comment]
@spkellyo What we see in the image you attached is the \<oXygen/\> Author view, a different way of viewing an XML document within \<oXygen/\>, in which all of the tags are replaced with little triangles (only in the way the file is displayed; the real markup is still there under the surface). You can fix this by finding the line (typically at the bottom of your \<oXygen\> interface, but in the upper right corner in some versions) that says “Text Grid Author” and clicking on “Text”. If that doesn’t work, and you can stop by with your laptop, we can show you how to get back to where you need to be. I (David) will be in my office for the rest of the day today (Monday, February 25), at least until 6:00 p.m. If that time doesn’t work for you, let us know and we’ll fix an appointment with one of the instructors.

**Comment by spkellyo** [comment]
That fixed it. I had to click on a few things, but now its back. Thanks!
