### ISSUE TITLE
Class discussion post: Guidance for Schematron

### ISSUE THREAD

**Issue by brenda275** [obdurodon/dh_course#280]
As I was working on the first schematron assignment I couldn't figure out what condition to put under the rule element. That is, understanding the difference between sum(), count(), and number(). I came across this [GitHub issue](https://github.com/ebeshero/DHClass-Hub/issues/375#issue-265532584) from another DH course at Pitt Greensburg that I found to be very helpful.

**Comment by djbpitt** [comment]
@brenda275 Thanks! Our course collaborates closely with the Greensburg one, and if the schedules align, we’ll arrange for joint project presentations at the end of the semester, as we’ve done in the past. 

Meanwhile, to the extent that it helps:

1. `sum()` takes a sequence of numerical values and adds them. If you have a bunch of `<price>` elements in your XML, you can get the total price with `sum(//price)`.
1. `count()` counts up the number of items in a sequence of any type of object. If you run `count(//price)`, you’ll count the number of `<price>` elements in your XML, but you won’t learn anything about what the actual prices are. You’ve already used this function in your XPath homework to count lines in speeches in *Hamlet*.

You can use `sum()` and `count()` together to calculate an average. For example, `sum(//price) div count(//price)` returns the average price. But there’s also already an `avg()` function, so you don’t have to make up your own!

`number()` converts a string (or something that XPath thinks is a string, even when a human doesn’t, like a page number retrieved from an XML element) to a number. We saw a place to use that in our recent in-class Schematron activity, where my not doing it when it was needed led to an incorrect result.
