### ISSUE TITLE
Quote triggering an error message in Shematron 

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#289]
I'm trying to include quotes in part of my schematron test but it is triggering the error "Element type "assert" must be followed by either attribute specifications, ">" or "/>"." Is there something I can do to escape them (like using &lt; rather then `<`) or is there no reason to use quotes in a test?

**Comment by zme1** [comment]
@sjw82 When we use nested quotes, we need to alternate between double quotes (`”`) and single quotes (`’`), or else the parser won’t be able to interpret our value.

Here’s an arbitrary example of those nested quotes in a Schematron rule:

```
<rule context=“s”>
<assert test=“contains(., ‘Hi, mom!’)”>This is a descriptive Schematron error message!</assert>
</rule>
```

Above, I’m setting my rule context on `s` (for sentence), and verifying whether or not that `s` element contains the string “Hi, mom!” which is contained by single quotes, to distinguish them from the quotes that surround the entire attribute value. 

Based on what you’ve written here, it seems like that may be your issue. If I misunderstood you, let us know!
