### ISSUE TITLE
Monday comment

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#29]
With regard to the site that we viewed for our reaction, do we ever delve into the design of interactivity to the extent that there is on this site?  I'm probably getting way to far ahead of myself but I'm just curious after checking the site.

**Comment by brucknerp** [comment]
Correct me if I'm wrong, but you're asking about whether we are going to add interactive elements to our own sites? 

I think it is a personal preference based on the nature of your research question and the amount of time you guys have to devote to developing these modules. I know there are some past Comp Hum. projects that allowed the visitor to click and select what kind of data they wanted to see visualized (My immortal, IIRC), so if it will work well in your project, I'd say go for it! 

We also don't have to be scholars outlining the entirety of the Roman communication network, so there's less pressure to create some crazy interactive site like Orbis. :) Just do what is natural for your site.
