### ISSUE TITLE
Multiple HTML Pages, One CSS Document?

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#290]
Is it better to try and accommodate all html pages with one style sheet or to have multiple CSS documents? I found this on how to work everything in one document (https://www.codecademy.com/en/forum_questions/50c812cbd1fe08c2a2000b70), but I don't understand which would be the more apt choice.

**Comment by gabikeane** [comment]
We recommend one CSS document for your whole site.
That way, when you make a change to a margin on your nav (or something similar) that change is reflected across the whole site.
There isn't really a benefit to having multiple. If you have functionality that you only want to work on one page, just make sure the class you use to style that element is unique to that page.
