### ISSUE TITLE
Discussion Post-XSLT

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#292]
I had the XSLT document up and running while we were doing the quick run through in class on Monday, however I'm in my document now and it's not giving an output and gives the warning message: "The source document is in namespac http://www.w3.org/1999/XSL/Transform, but none of the template rules match elements in this namespace (Use--suppressXsltNamespaceCheck:on to avoid this warning)". I haven't touched the document since the last time it was working, but I'm assuming the problem lies somewhere within the first 6 lines of the document. Here's a snippet of my first 6 lines:
`<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0" version="3.0">
    <xsl:output method="xml" indent="yes" doctype-system="about:legacy-compat"/>
    <xsl:template match="/">`

**Comment by rmf96** [comment]
Rubber Duck debugging strikes again.... I didn't have the bad-hamlet doc open. Nice one.

**Comment by djbpitt** [comment]
@rmb165 We’ve all been there ...
