### ISSUE TITLE
How to email xslt

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#293]
I'm unable to open the xslt document I sent myself, which we did in class. Is there something we're supposed to do to be able to open it?

**Comment by djbpitt** [comment]
@MLuckman You need to tell us what you mean when you write that you are not able to open it. How are you trying to open it? What happens when you try?

**Comment by MLuckman** [comment]
I sent it to myself as a .xsl file. Outlook seems to not even recognize as a file, the usual options to download or save just don't exist, clicking on it has no real effect - I can drag the icon around but it has no real effect.

**Comment by djbpitt** [comment]
@MLuckman I haven’t seen this issue before. Can you please bring your laptop into class and we can take a look at it? Please also forward the email to me just as is, with the attachment still attached, using my Gmail account at djbpitt@gmail.com. Thanks!
