### ISSUE TITLE
XSLT question: XHTML tab

### ISSUE THREAD

**Issue by AncientGreekGeek** [obdurodon/dh_course#298]
I was able to get through most of the assignment, but for some reason I had some trouble trying to figure out the output popup window. For some reason only the text tab appears for me, instead of both the text and the XHTML tabs. I didn't really have an issue with that, but I'm wondering if there's anything I can do to make sure I can see both tabs so that I can use view the XHTML version if necessary in the future?

Thanks!

**Comment by Guifindor** [comment]
@AncientGreekGeek to the right of the drop down menus where you select your XSLT and XML document for the debugger (same row), there should be a button that has two angle brackets, a slash between them and HTML in tiny print. Select that and there should be an HTML tab next to your text tab in the output.

Edit: You have to run your xslt debugger once with that option turned on for the HTML tab to appear

**Comment by djbpitt** [comment]
Thanks, @Guifindor!
