### ISSUE TITLE
XSLT Debugger Error Message

### ISSUE THREAD

**Issue by pickettj** [obdurodon/dh_course#301]
I'm getting an odd error message during XSLT debugging. It seems to run fine anyway, but still strange.

Every time I click "debug" it tells me that Saxon-HE is not up to 3.0 snuff; but I am fairly certain that HE is the correct version. Screenshot:

![image](https://user-images.githubusercontent.com/25989796/53985007-918c6b80-40e8-11e9-8c7f-96b1a1c2ce46.png)

Here are the settings I have at the top (I suspect something in there is toggled wrong):

```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0"
    xmlns="http://www.w3.org/1999/xhtml">
    <xsl:output method="xml" indent="yes" doctype-system="about:legacy-compat"/>
```

**Comment by djbpitt** [comment]
@pickettj I’m not sure what’s going on here. Can you please bring your laptop to class and we can look at it there?

**Comment by pickettj** [comment]
Upgrading to new version of Oxygen indeed fixes this issue.
