### ISSUE TITLE
March 8th Project Update

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#303]
This past week I read the poems and noted the different nouns used to refer to women. I also thought about the content markup and how I want to eventually categorize the words used to depict or note women. I definitely need to differentiate between familial and non-familial relationships. Mitchell did a similar thing with the English source. He began the content markup, which will use trojan tags (I think that is what they are called). We worked on this during our project meeting, where we also decided what our midterm tasks will be. Mitchell and I are to finish the thematic markup on our respective sources, his will edit the css of the website so the menu will remain in a fixed position, I will update the README.md so Daniel can copy a newer version onto the website, and we will both work on using xslt to make a reading view (if we have the time to start). Daniel standardized the CSS across all pages of the site, updated the background image with a non-copyrighted photo. He will work on implementing server side includes and his midterm goals are to delete the unnecessary stylesheet link, to figure out why the home and project pages do not appear the same, and to delete extraneous css files.

In general, we all need to think about the modes of access we want, especially in terms of how we want to organize the poems by topic and how we want users to be able to navigate through. We also need to think about the graphical representations that we want, "what story we want to tell" -Dr. Birnbaum-Mitchell Luckman-Emma Mamula.

**Comment by djbpitt** [comment]
@emmamamula Thanks, Emma, but can you please post this as an issue in your project repo?

For those eager to learn more about standoff markup, there’s a good overview (well, if you can bear the bad puns) of some of the strategies, including the Trojan milestones that Emma mentions, at <http://conferences.idealliance.org/extreme/html/2004/DeRose01/EML2004DeRose01.html>.
