### ISSUE TITLE
Problem installing MALLET

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#304]
I downloaded and unzipped mallet into my applications but the command line can't find it. Is there something special that I have to do? I'm on a mac if that changes anything. Also, I'm using [this tutorial](https://programminghistorian.org/en/lessons/topic-modeling-and-mallet) and it claims I need to download a special form of Java. Is that really the case?

**Comment by gabikeane** [comment]
Hi Sam!
Yes, you do need to have Java Developer Kit for Mallet. Installing this on a Mac shouldn't be too terribly complicated after the Java install, but let me know if you run into more issues!
