### ISSUE TITLE
Our index file now shows up as a Chrome file in Repo

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#306]
I went to look at our index file and when I tried to open it in Oxygen it opened as a Chrome file. I right clicked the page and copy and pasted the code into another xhtml file, but when I saved that one it did the same thing (I renamed it). Clearly this is something simple, I just don't know what I did. Thanks for your help!

**Comment by djbpitt** [comment]
@spkellyo Can you be more precise about where you are looking at the file? For example: On your project site on Obdurodon at <http://sherlock-orient.obdurodon.org/>? In your repo on GitHub at <https://github.com/loreese/sherlock/blob/master/index.xhtml>? As a “raw view” in your repo on GitHub at <https://raw.githubusercontent.com/loreese/sherlock/master/index.xhtml>? On your local filesystem, from your local clone of your repo? Somewhere else?

I think you’re right about a simple wrong turn being at work here. If you can tell us in a more specific way about how you went to look at your index file and, also in a more specific way, how you tried to open it in \<oXygen/\>, that might help us figure out where the misunderstanding lies.
