### ISSUE TITLE
XSLT 3 (CSS)

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#307]
I'm having an issue when uploading the CSS file. I scan the file with my antivirus to see if there was an issue and it was fine. What shoul I do?

<img width="1046" alt="Screen Shot 2019-03-17 at 9 31 05 PM" src="https://user-images.githubusercontent.com/46380238/54501496-06874e80-48fc-11e9-9787-34bac32b772d.png">

<img width="831" alt="Screen Shot 2019-03-17 at 9 33 01 PM" src="https://user-images.githubusercontent.com/46380238/54501547-4e0dda80-48fc-11e9-83d0-4731d55704af.png">

**Comment by zme1** [comment]
@ddaud02 How about you email me a copy of your CSS file when it's all done?

**Comment by ddaud02** [comment]
Hi Zack, here is my CSS for XSLT # 3.
________________________________
