### ISSUE TITLE
CSS Flexboxes: just for fun

### ISSUE THREAD

**Issue by ebeshero** [obdurodon/dh_course#31]
Here's a game to help learn CSS flexboxes: 
http://flexboxfroggy.com/

and another (in case you don't find amphibians appealing):
http://www.flexboxdefense.com/

**Comment by gmd29** [comment]
Thanks for sharing this! I feel like I need some extra practice with CSS and I think these will be helpful.

**Comment by djbpitt** [comment]
Who doesn't like amphibians? A very enjoyable workout! Thank you!

**Comment by ebeshero** [comment]
The students in [the "sibling" course](http://dh.newtfire.org), dominated by the figure of a Japanese firebelly newt, were happily playing with frogs after class today. We are amphibian appreciators here. ;-)

**Comment by JosephDRogers23** [comment]
I love the FlexBox Frog game! It makes me wonder how much crossover there is between basic CSS and animation/graphic design - someone with advanced animation skills made this site, and I wonder how much CSS they've had to use in their career to design web pages such as this, as compared to other animation languages.

**Comment by djbpitt** [comment]
For information about CSS animation, see <https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations> and <https://robots.thoughtbot.com/css-animation-for-beginners>.
