### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#310]
Trying to create the first portion of my drop down menu for the website. Thought I had everything coded correctly, but when you hover over the button it's still a cursor and you're not able to click on it... css below:

`h1 {
    background-color: LightSkyBlue; text-align: center; 
}
body {
    background-color: Tomato;
}
#Home {
    
}
#Dropdown {
    
    position: absolute;
    }
#pages {
    display: none;
}
#list:hover #pages {
    background-color: black;
    display: block; 
}`

**Comment by MLuckman** [comment]
I'm not doing this portion of our project, but I know that there's a semi-functioning drop-down on our site, http://serb-songs.obdurodon.org/conclusions.xhtml

If you inspect source you can probably find some of the problem, and @ddaud02 might be able to help out because he did it on ours.

**Comment by djbpitt** [comment]
@rmf96 To change the shape of the mouse cursor on hover you need to set the value of the `cursor` property. See <https://developer.mozilla.org/en-US/docs/Web/CSS/cursor>. Note that you can change the value on hover with the `:hover` pseudo-selector, about which see  <https://www.w3schools.com/css/css_pseudo_classes.asp>.
