### ISSUE TITLE
Project Formating for Website Pages

### ISSUE THREAD

**Issue by k-busko** [obdurodon/dh_course#311]
So I accidentally did the response paper that is due Friday (whoops) but it brings up a good point regarding our projects. When it comes to assigning people for different pages, the slight variations between creators collaborating can affect the overall user experience to the degree. Of course, you wouldn't make one group member work on all the pages of a website but are there any past experiences with how to create a conducive and flowing website, one where its not obvious that a different person worked on a certain page?

**Comment by Guifindor** [comment]
I have vaguely done group work on HTML before (This was with a project using the IONIC framework, so no traditional webpages like in this class), but for the most part not much. I did most of the HTML/CSS so there was not much collaboration per say, but these were loosely the steps I followed anyway:

1. Draw up a physical view of the website, or have someone work on a prototype page
1. Settle upon a style based off of this prototype (i.e. layout, symbol convention, images, e.t.c.)
1. Peer Review each other's work in set intervals. For our project this could simply be quick reviews during weekly meetings
1. When finished with an iteration, have someone outside your group review your work
1. Repeat 1 & 2 for as many different styles you need (most of the time it should be just once though)
1. Repeat 3 & 4 until finished

Having someone else other than you review your work is the most important step. Even if you have an agreed upon layout and style, you might end up doing something different in areas that were not explicitly defined (I end up doing this quite a bit myself). Regardless of how objective you are, you are going to be biased to your work in some regard, so consulting someone else's perspective is important. Having someone from a different background among the reviewers is preferable. By assembling opinions from quality peer reviewing, you should be able to iron out most of the wrinkles regarding this issue you presented.

Of course, that's just my opinion. I have not read the prompt nor source material for this Friday, and like I said, I have not done much, just one group programming project that included visual design by HTML/CSS.
