### ISSUE TITLE
XSLT #4 

### ISSUE THREAD

**Issue by AncientGreekGeek** [obdurodon/dh_course#313]
I had a lot of trouble figuring out how to put in the line breaks. I tried to put it directly into the html as suggested and that didn't work and I also tried to put them in using a <xsl:if> element, which also didn't work. I'm not sure what else to try.

**Comment by djbpitt** [comment]
@AncientGreekGeek 

```xml
<xsl:template match="line">
    <xsl:apply-templates/>
    <xsl:if test="following-sibling::line">
        <br/>
    </xsl:if>
</xsl:template>
```
