### ISSUE TITLE
Question about Project Aesthetics

### ISSUE THREAD

**Issue by Nerdologist** [obdurodon/dh_course#314]
Our TA project advisor said some aesthetic criteria would factor into the grades for our projects. I am wondering if those criteria will include the visual elements of the UI techniques described in _Visual usability: principles and practices for designing digital applications_ by Tania Schlatter and Deborah Levinson and _Designing Web Interfaces_ by Bill Scott and Theresa Neil. If so, which of those techniques are most important to implement in the development of our websites, and in what ways, broadly speaking, should we implement them? Also, is our use of these techniques, which as I understand them mainly serve to keep the site clear and functioning conveniently, all that counts toward the aesthetic portion of our grade? Or do we need to go above and beyond what is required to maximize the usability of our websites, in order to get full credit?

**Comment by zme1** [comment]
@Nerdologist In a general sense, when we evaluate the finished project sites, we look to see how effectively you use your site to tell the story of your research, how clearly that story is communicated to your audience, and how easily that same audience can navigate and interact with your features. We don't necessarily expect X, Y, and Z features when we look at the project interface, although we do expect all groups to have some form of a reading view available on their page and accompanied, quantified analyses of any phenomena that you find in support of your research. When it comes to building and presenting your host site, you can operate with full creative liberty and under the presumption that if you *want* to do something but don't know exactly *how* to do it, the instructor team (and especially your mentor) will be more than happy to help make that happen.
