### ISSUE TITLE
CSS on different computers/macs

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#315]
I'm having some issue while doing CSS coding, the menu looks fine on my MacBook however, on my iMac looks completely different. Does anyone know how to fix it? 

**Mackbook**
![FullSizeRender](https://user-images.githubusercontent.com/46380238/54769961-af71ca00-4bd8-11e9-92b8-0563aa1d7cbf.jpeg)

**IMac**
![FullSizeRender-1](https://user-images.githubusercontent.com/46380238/54770069-e516b300-4bd8-11e9-8920-482d53179be4.jpeg)

nav {
    display: flex;
    flex-direction: row;
    justify-content: center;
}
/* submenu positioning*/
.nav ul {
    position: fixed;
    white-space: nowrap;
    border-bottom: 5px solid orange;
    z-index: 1;
    left: -99999em;
}

**Comment by djbpitt** [comment]
@ddaud02 If this were me, I’d use Git to back up to just before it broke in order to try to find the code that broke it. We can go over how to do that in our team meeting.
