### ISSUE TITLE
Submitting on courseweb issue

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#317]
I'm trying to submit XSLT 5 on course web and I'm getting the following message:

You can't attach the following file. It may contain a security threat: fox_03-22_XSLT5.xsl Please fix the file and re-attach it OR attach a ZIP of the file.

How do I fix this so that I can submit?

**Comment by gabikeane** [comment]
Zip the file into a folder or add a .txt after the file name so it doesn't interpret it as a threat.

**Comment by rmf96** [comment]
Thanks!
