### ISSUE TITLE
refresh on fetch uploads/accessing site space

### ISSUE THREAD

**Issue by loreese** [obdurodon/dh_course#318]
It's been quite a while since I put anything up on our project site, and I am entirely lost on how to access our site space. When I connect to the server, I use obdurodon.org and can access the server space where we uploaded our first few HTML/CSS assignments, but can't remember where our actual project space is or how to get there through the backdoor. I've tried a few different approaches and am not sure if the Hostname, Username, or something else entirely is different in the process. Hoping I'm not the only one in this boat?

**Comment by zme1** [comment]
You need to navigate to `/var/www/html/sherlock` to access your project directory. In Fetch, click on the icon labeled "Paths", along the top tool bar. Then click on the `/`, which will take you to the top of the server space. From there, follow the listed file path to access our project space.

**Comment by loreese** [comment]
@zme1 Got it, thanks!
