### ISSUE TITLE
Took quotation marks out of xml need to put them back in html

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#319]
When we marked up our xml we were told to take out the quotation marks. In very line of text in a paragraph that had dialogue we took out the quotation marks and wrapped the dialogue in tags.
`<q speaker="Watson">I dare say, </a> I remarked as I filled my pipe. <q speaker="Watson">We should look out for that fellow.</q></p>`
As you can see the quotation marks can go anywhere. We also have instances of single quotes, but I won't worry about that yet. I just need the double quotation marks back in. Do I use apply-templates? I tried `<xsl:text>"</xsl:text>` but that made a mess. Any advice would be great. Even a website, I've been googling all night and I can't find out how to do this. Thank you!!!!

**Comment by djbpitt** [comment]
@spkellyo Match `<q>` elements in the input and output `<q>` elements in the output. By default browsers will insert straight quotation marks at the beginning and end of each quoted snippet. With CSS you can get curly quotation marks, and also automatic alternation of double and single quotes when they’re nested, but the first step, as you note, is to write HTML `<q>` elements into the output.
