### ISSUE TITLE
Site Reload after pushing XHTML and CSS

### ISSUE THREAD

**Issue by Ethandaniel47** [obdurodon/dh_course#320]
I've recently uploaded all of my XHTML and CSS documents for our preliminary page, however when I try to view these changes on the site, a page comes up from "Apache 2 Test Page" telling me that the site is under some sort of maintenance. Is this typical?

http://poe.obdurodon.org

**Comment by gabikeane** [comment]
Is your home page called index.xhtml?

**Comment by Ethandaniel47** [comment]
It is not, I assume that it should be?

**Comment by gabikeane** [comment]
Yep, that's the file the server looks for when you make a request to that web address. After that, all of your linked pages can be called whatever you'd like-- the URL will be that initial web address + /filename.xhtml.

Hope that helps.

**Comment by Ethandaniel47** [comment]
Yep, all good now. Thanks!
