### ISSUE TITLE
CSS Issue with Bullet Points

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#321]
I'm having trouble getting bullet points to show up on my site.
My CSS:
`#discussiontext {
    display: none;
    font-size: 15px;
    list-style-type: circle;
}
#discussiontext ul {
    font-size: 15px;
    list-style-type: circle;
}
#discussiontext ul li {
    font-size: 15px;
    list-style-type: circle;
}`
And then what its putting out
<img width="867" alt="Screen Shot 2019-03-24 at 5 58 25 PM" src="https://user-images.githubusercontent.com/46945633/54886452-721e6e00-4e5e-11e9-8833-d309f1d8c1c5.png">

You can see I put list-style-type everywhere trying to figure out where it would work, but I can't make it do anything. Changing the font size works so I know that the CSS sheet is connected and that the ID is correct.

**Comment by djbpitt** [comment]
@sjw82 The `display` value of your `<li>` elements has to be `list-item`, and not `block`, if you want the bullets to be displayed.
