### ISSUE TITLE
Is it possible to link to a page with hidden content visible?

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#322]
I have a page that has visible content with a button that reveals hidden content using javascript. In my table I have a link to the page with the plain visible content. Is there a way to link to the page so that the button has already been activated?

**Comment by djbpitt** [comment]
@sjw82 If I've understood the goal correctly, you can set an event handler on the link that will not only traverse the link, but also activate the button. For example, if you click on the link to go to the page, that click can also fire a JavaScript function that will do whatever manipulation you could have done through the button.
