### ISSUE TITLE
SVG in-class code now available!

### ISSUE THREAD

**Issue by zme1** [obdurodon/dh_course#326]
Hello everyone,

A copy of the file that we made during class today to output our SVG visualization is now available in the repo. Let an instructor know if you have any questions!

Best,

Zac

**Comment by ddaud02** [comment]
@zme1 could you write here the link, there is a lot of information on the site.

- w3schools introductory SVG tutorial (good, basic introduction; start here for a quick initial overview with brief examples of the most common features)
- Jakov Jenkov SVG tutorial (also introductory, but longer and with more detail than the preceding; start here for something more comprehensive)
- SVG cheat sheet (Washington State University)
- How to scale SVG (Amelia Bellamy-Royds’s tutorial about how scaling SVG doesn’t work like scaling othe types of images).
- By Sara Soueidan:
- Building better interfaces with SVG
- Understanding SVG coordinate systems and transformations (Part 1) — The viewport, viewBox, and @preserveAspectRatio
- Understanding SVG coordinate systems and rransformations (Part 2) — The @transform attribute
- Making SVGs responsive with CSS
- On-line SVG editors: Method draw | svg-edit
- Software: Inkscape (open-source vector graphics editor; see also Aaron Nieze’s rich assortment of Inkscape tutorials)
- Tutorial: Using XSLT to generate a bar graph
- Embedding SVG in XHTML
- Trigonometry refresher (in case you need to plot circular locations)
- SVG assignment #1
- SVG assignment #2
- SVG assignment #3

**Comment by zme1** [comment]
@ddaud02 we pushed it to this repository after class yesterday, and it’s not on our course website. My apologies for the confusion. It’s available in the svg folder on the main page that contains all our code.

**Comment by djbpitt** [comment]
https://github.com/obdurodon/dh_course/tree/master/svg
