### ISSUE TITLE
Writerly Text and the Lo-Fi Manifesto

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#327]
I read *The Hermeneutics of Screwing Around; or What You Do With a Million Books.* I thought that the writerly texts discussed at the end were similar to the Lo-Fi Manifesto in that they both (by my understanding) seemed to advocate for/appreciate anarchic/open-source/decentralized systems as a way of doing scholarship.

**Comment by zme1** [comment]
@MLuckman We forgot to post the Single-Issue forum until after you posted this (our bad). Would you mind relocating your response to the Issue for your selected reading?
