### ISSUE TITLE
Question About the Test

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#33]
What's up, everyone!
I've finished the test, to mostly my satisfaction (even if it took 2 hours and 13 steps), but I was wondering how to get the one thing I was unable to fix. There are characters whose names include periods -- but my searches for speakers depend on periods terminating the name. Anyone know a way to work around that aside from manually searching for one specific character? Thanks!

**Comment by jachinn** [comment]
It looks like the number of spaces after a period in the middle of the name
differs from the number of spaces at the end of a name...

**Comment by djbpitt** [comment]
For those who don't recognize the @jachinn who responded to @Idi0teque’s question in this thread, she’s <http://imm.dh.obdurodon.org/about/janis/>. Thanks, Janis, and welcome back!

**Comment by brucknerp** [comment]
I'm not sure if you meaning searching for one specific character as in a person's name or as in a single text character but I remember my answer being really convoluted (in my opinion), making the spaces @jachinn or period you mentioned optional. 

Follow-up question, did people find a one-line answer that accounted for multiple speakers of a single line, not just characters with a title? There were at least two examples I found that I couldn't get with regex so I just manually tagged after.

**Comment by zme1** [comment]
@brucknerp Our solution tagged speakers like Two Male Voices in one `<speaker>` tag. Aside from that, speakers like that did not seem to change the criteria of our search too much. There are specific textual patterns, like @jachinn mentioned, that we were able to use as markers in our searches to find all our speakers at once.
