### ISSUE TITLE
SVG 2 Question

### ISSUE THREAD

**Issue by MLuckman** [obdurodon/dh_course#330]
This all liberally borrows from the in-class code, including keeping `preceding-stooge` as a variable name because I thought it was funny. Something is broke in my code though, it won't even draw the x-axis and I haven't gotten any boxes to show up. What's wrong?

```<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs" version="3.0"
    xmlns="http://www.w3.org/2000/svg">
    <xsl:output method="xml" indent="yes"/>
    
    <xsl:variable name="bar-width" as="xs:integer" select="75"/>
    <xsl:variable name="bar-interval" as="xs:integer" select="25"/>
    <xsl:variable name="xlength" as="xs:integer" select="5000"/>
    <xsl:variable name="ylength" as="xs:integer" select="300"/>

    <xsl:template match="/">
        <svg>
            <g transform="translate(80,500)">
                <line x1="0" y1="0" x2="{$xlength}" y2="0" stroke="black" stroke-width="1" stroke-linecap="square"/>
                <line x1="0" y1="0" x2="0" y2="-{$ylength}" stroke="black" stroke-width="1"/>
                <xsl:apply-templates select="//candidate[@party='Democrat']"/>
            </g>
        </svg>
    </xsl:template>
    <xsl:template match="candidate[@party='Democrat']">
        <xsl:variable name="percent" as="xs:integer" select="."/>
        <xsl:variable name="preceding-stooge" as="xs:integer" select="count(preceding::candidate[@party='Democrat'])"/>
        <rect x="{$bar-interval+($bar-width+$bar-interval)*$preceding-stooge}" y="-{$percent}" height="{$percent}" width="{$bar-width}" fill="blue" stroke="black"/>
        <text x="{$bar-interval+($bar-width+$bar-interval)*$preceding-stooge}" y="15" text-anchor="middle">
            <xsl:value-of select="ancestor::state/@acro"/>
        </text>
    </xsl:template>
</xsl:stylesheet>
```

**Comment by rmf96** [comment]
Hi! I'm actually at a really similar spot... I just don't understand where the calculating of percentages comes in? I don't understand if we're supposed to calculate each of the percentages ourselves or somehow write code in order to do so..? Right now, I'm stuck with like a billion blue boxes with basically no numerical significance. Big sad.

**Comment by djbpitt** [comment]
@rmf96 Forget about the chart for a moment and imagine that you have to calculate the percentage of Democratic votes for each state just as a number. It’s an arithmetic formula: Democratic votes divided by total votes (add up all four parties) and multiply by 100. The next step is to implement that in your XSLT: XPath can add, multiply, and divide, so you can write the process as arithmetic inside the template that processes each state.

**Comment by djbpitt** [comment]
@MLuckman If you write your code step by step, and test it after every step, you’ll save yourself a lot of debugging time. Strip it down to just the axes (no rectangles, no text) and see whether you can get them to render properly. Use all three means at your disposal to check: view it in a browser, look at the angle-bracketed output (are there values for all of the attributes? do they look sensible?), and save and validate it in \<oXygen/\>. Once that’s working, add just one small feature at a time, and check after every step.
