### ISSUE TITLE
300- to 400-word response paper to Zelda, Rap, or Lega that focuses on visualization.

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#333]
Hi, can anyone point me where can I read these papers/projects? I can not find them.

**Comment by zme1** [comment]
You can view all our course projects, past and present, on the [course projects](http://dh.obdurodon.org/course-projects.xhtml) page on obdurodon. The Zelda project is available at [http://zelda.obdurodon.org](http://zelda.obdurodon.org); Rap is available at [http://joey.obdurodon.org](http://joey.obdurodon.org); Toscana is available at [http://toscana.newtfire.org](http://toscana.newtfire.org). I hope this helps!

**Comment by ddaud02** [comment]
Thanks, @zme1
