### ISSUE TITLE
Weird and urgent angle bracket problem

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#336]
When typing `<` in oxygen it is automatically converting to `&lt;`. How do I fix this?

**Comment by djbpitt** [comment]
@sjw82 You’ve been typing angle brackets in \<oXygen/\> all semester and they’ve functioned as markup angle brackets, without being turned into character entities. So you need to tell us more about what is happening now, and in what circumstances, that makes the behavior different from what you’ve done to enter angle brackets successfully in the past.

**Comment by sjw82** [comment]
@djbpitt It was just one document started doing it, so I copied the content into a new document and it's working fine. I guess I must have clicked on some setting in the document that changed it. It would convert to a character entity whether it was typed, copied and pasted, or inserted using command+e.

**Comment by djbpitt** [comment]
@sjw82 I’m relieved to learn that you’ve been able to work around the problem, but if the original document is still doing it, please bring it to class so that we can try to figure out what’s going on.
