### ISSUE TITLE
XQuery uses XPath 3.0 to navigate documents

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#337]
Hi, the XQuery-XPath tutorial says that it uses 3.0 to navigate documents when I open the Exide program it says version "3.1", should I rewrite that number to "3.0"?

**Comment by djbpitt** [comment]
@ddaud02 Good eye! eXist was updated from XPath 3.0 to 3.1 fairly recently. Since 3.1 is backward compatible with 3.0, you can just leave it as 3.1.
