### ISSUE TITLE
42 Shakespeare plays or 43 ?

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#339]
XQuery Exercise number 1 says that: Use the 42 Shakespeare plays that have been uploaded to Obdurodon to do the following... When I use the codes **collection('/db/apps/shakespeare/data')** , it gives me 43. 

![43](https://user-images.githubusercontent.com/46380238/55689213-d0b01580-594f-11e9-9616-e7b978d880bf.jpeg)

**Comment by djbpitt** [comment]
@ddaud02 Yep. There’s one non-play document in the collection, which is part of specific project built around the plays. That 43rd document is not in the TEI namespace, so as long as your queries use the TEI namespace correctly, you won’t encounter any interference from it.
