### ISSUE TITLE
Much Bigger Question

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#34]
Hey everyone,
This is probably going to sound stupid, but no matter what I search in the Bad Hamlet XPath, I get "the XPath Query found no results," no matter how I change the scope. The only exception is when I searched for *, at which I got one result (called "xml:id="sha_ham"). I'm feeling like I'm losing my mind and I don't know what I'm doing wrong; any hints?
Thanks!

**Comment by djbpitt** [comment]
In the explorations we did in class, we began all of our paths with a slash as a way of saying “start at the document node”. If you don’t do that, your path begins wherever your cursor happens to be. For example, if your query reads `p` and there are no `<p>` children of where your cursor happens to be, you won’t find anything. But if your query reads `/descendant::p` (note the leading slash), you’re saying “wherever your cursor happens to be doesn’t matter; start this path from the document node, and look for `<p>` elements on the descendant axis from there”.

**Comment by Idi0teque** [comment]
Oh my god I forgot the slash!!! Thank you so much!
