### ISSUE TITLE
Trouble with Table of Contents title

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#340]
My table of contents shows up more or less the way I want- still working on font sizing. But the title Table of Contents will not appear as a title in the `<ul>` Here is how it is right now:
`   <div id="toc">
                    <h3>Table of contents</h3>
                <ul>
                    <xsl:apply-templates select="//ch" mode="toc"/>
                </ul>
                 <xsl:apply-templates/>
                </div>    
            </body>
        </html>'
The words show up, but in my CSS I have a background image and it will not sit on top of the toc on top of the background image.  This is what I put:
`div.toc {
   background-image: url('../images/parchbk.jpg');  
    width: 35%;
    height: auto;
    padding: 25px;
    margin: auto;
}

ul {
    background-image: url('../images/parchbk.jpg');
    list-style-type: none;
    text-align: center;
    width: 300px; 
    margin: auto;
    padding: 20px;
    border: 2px;
}`
Does anyone know how to fix this? It's making me crazy. I've tried moving the text Table of Contents, but then it just disappears. I don't have anything to match it to, so I can't use apply templates. Thanks!

**Comment by djbpitt** [comment]
@spkellyo Is the background image located where the URL is pointing?
