### ISSUE TITLE
Plain Text File

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#341]
Hello, I finish the XQuery Exercise number 1 and I'm having problems using a regular plain text file. I do not how to make a list, I tried the same pattern as we did with MD files (markdown) and it is not working. I might just copy all my answers from a Microsoft word file directly the plain text.

**Comment by djbpitt** [comment]
@ddaud02 If you’re asking how to output text with new lines, you can change the pulldown over the eXide output panel from "Adaptive output", which is the default, to "Text".
