### ISSUE TITLE
Using SVGs to turn images into links

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#342]
[Here](http://thenewcode.com/760/Create-A-Responsive-Imagemap-With-SVG) is a resource for creating imagemaps out of svgs and [this](http://thenewcode.com/696/Using-SVG-as-an-Alternative-To-Imagemaps) explains why to use them. These can be helpful if you want to make parts of an image link to other pages. Their [reading list](http://thenewcode.com/699/Web-Developer-Reading-List-SVG-Imagemaps-Interactivity) also details how to make information pop up when part of an image is clicked, create an interactive geographical map, and a cool thing where you can make the rest of an image go gray when you hover of one feature.

**Comment by gabikeane** [comment]
Thank you Sam! What a great resource!
