### ISSUE TITLE
Problem downloading eXist

### ISSUE THREAD

**Issue by spkellyo** [obdurodon/dh_course#343]
I'm a little confused about how to download eXist. I went to the website, clicked "Latest Stable Release", clicked "Set me up" and then got this message below. Sorry for the screen shot, I don't know how else to do this or how to fix it up so you can see just the box. What is Curl? Should I download that too? I clicked on Files and it had several there with file extensions that are new to me, so I didn't want to click anything and get a virus. Are there instructions on Obdurodon that I missed? Thanks for any help.
![image](https://user-images.githubusercontent.com/46850090/55757783-ea6e5d00-5a22-11e9-8e86-3221a29e7c63.png)

**Comment by gabikeane** [comment]
To do this assignment, you don't need to have a local copy of eXist-db. Instead, navigate to obdurodon.org:8080 and click on eXide, the eXist-db integrated development environment.

If you would like to use eXist-db locally for your project, please see an instructor for assistance with installation. It's kind of complicated no matter if you're on Mac or PC.

**Comment by djbpitt** [comment]
@spkellyo That’s a very user-unfriendly notification from our friends at eXist-db! Curl is a command-line tool for downloading files over the Internet. You shouldn’t need it for the download and installation, though, and I’m not sure why the site is showing you that message. 

As @gabikeane writes, if you’d like to install a local copy of eXist-db on your own machine, it may be simplest if you do the download and installation with one of us. Normally we’d encourage everyone to install their own copy, but given the end-of-semester time pressure and the fact that installing your own instance of eXist-db isn’t required, you might reasonably decide not to do it right now. But if you’d like to, let us know and we’ll help.
