### ISSUE TITLE
XQuery question

### ISSUE THREAD

**Issue by rmf96** [obdurodon/dh_course#345]
I tried placing the distinct-values element next to both `tei:TEI` and `tei:speaker` and I'm getting 0 items returned in my count. I feel like the distinct-values part should be going somewhere else but I'm not sure where it would be appropriate?

**Comment by djbpitt** [comment]
@rmf96 The easiest way to think about where to put `distinct-values()` is to see start by writing an XPath expression that returns all of the items you care about, including the duplicates. Once you can do that, if you wrap `distinct-values()` around that entire expression, it will deduplicate it.
