### ISSUE TITLE
XQuery Number 2 is marked wrong on Blackboard

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#346]
XQuery Number 2 is marked wrong on Blackboard 

<img width="448" alt="Screen Shot 2019-04-09 at 8 27 27 PM" src="https://user-images.githubusercontent.com/46380238/55843406-1c0c2480-5b06-11e9-8539-98f309ac1dd3.png">

**Comment by zme1** [comment]
@ddaud02 We fixed the mistake in the assignment description: thanks! To be clear, XQuery is due tomorrow, and XQuery 2 is due Friday.

**Comment by ddaud02** [comment]
@zme1 I made a "mistake" and finish XQuery number 1 by Monday the 8, I was going to start number 2 today, but now I can do other things instead. Thanks.
