### ISSUE TITLE
XQuery 1 confusion 

### ISSUE THREAD

**Issue by AncientGreekGeek** [obdurodon/dh_course#349]
I'm really confused about where to include the `count()` in part 3 of the XQuery 1 homework. It seems as though it should be either after the `tei:speaker` or around the whole expression `collection('/db/apps/shakespeare/data')//tei:speaker`, but neither of those options work, am I missing something?

**Comment by Guifindor** [comment]
To use the count function, you surround the expression you want to count. I don't know why it doesn't work on your second query, but your approach is completely wrong. Your XPATH expression would return ALL speakers for ALL plays, which is not what you want. Remember, you're using the count function to filter your results, not as your return value (unless you're just testing output for said filter function, then I retract that last statement).

**Comment by djbpitt** [comment]
Thanks, @Guifindor!

@AncientGreekGeek, the way we looked at this in class was to think about it in stages. Once we could get the titles of all plays, one way to get the titles of just the plays with more than 40 distinct speakers is to add a predicate in the path expression that filters the plays. Remember that predicates can occur at any path step, so you need to think about what you are filtering, and where. You can see how we did this for the XQuery 1 tasks in our posted solution.
