### ISSUE TITLE
Plain Text Files and Unicode

### ISSUE THREAD

**Issue by enb34** [obdurodon/dh_course#35]
I ran into an interesting problem while doing mark up on the Japanese version of _Alice_ earlier today. I was doing structural markup inside a plain text file, but I was unable to save any of my changes to the document because the characters weren't recognized by the document. I was able to figure out that this was due to the text files not being encoded in Unicode, but I was unsure how to fix this within the document.

This wasn't a huge roadblock, since xml files are automatically in UTF-8, and I was just able to convert the plain text file to xml without much difficulty, but I do like having a text file version of the texts I work with, so if anyone has any advice on how to tackle this problem in the future, that would be much appreciated.

**Comment by djbpitt** [comment]
When I have a non-Unicode plain text document that I need to convert to Unicode, I usually open it in BBEdit (Mac) or Notepad++ (Windows) and then save it as UTF-8 (without BOM, if it gives you the option). Both editors are free.
