### ISSUE TITLE
Transferring Updated Files to Project Site

### ISSUE THREAD

**Issue by Nerdologist** [obdurodon/dh_course#351]
Samantha started the website for our Midrash project, so I wasn't originally the one uploading files to the website. But now that I'm taking on the web development responsibilities, it's not enough for me to know how to commit and push the updated website files to GitHub; I also need to know how to upload these files to our website. I reviewed the "Putting content on line" reading (http://dh.obdurodon.org/mounting-projects.xhtml), and I asked a couple students for help, but I'm still lost. For one thing, I don't know how to navigate to our project directory. If it's relevant, I have a Windows computer, but Samantha does not. Would someone be so kind as to lay out the steps I need to take in SSH Secure Shell to transfer files from my local repo to the site? Thanks in advance.

**Comment by djbpitt** [comment]
@Nerdologist If it would be easier for you to stop by one of our office hours, we’ll be happy to go through the process with for you. But the basic steps are:

1. Use SSH secure shell. See the download link at the top of our Syllabus page. Don’t forget the permission setup described there; you only have to do it once, but if you don’t do it, you can make it impossible for your project teammates to upload files.
1. Connect to *obdurodon.org* using your Obdurodon userid and password. If you don’t remember what those are, tell me and I can reset them for you (the password is encrypted on the server, so I can’t look it up, but I can set a new one). You’ll need to use the Obdurodon SSH port number, which is not the default one. We don’t publish that number for security reasons, but ask anyone in the course and they should be able to tell you.
1. Once you connect with SSH secure shell, open an SFTP (secure file transfer) window. You can do that by clicking the yellow folder icon in the icon bar at the top of the SSH secure shell window after you’ve made the connection.
1. Your project is located at /var/www/html/midrash.
