### ISSUE TITLE
Pie Chart SVG Resource

### ISSUE THREAD

**Issue by sjw82** [obdurodon/dh_course#352]
After much searching (and wasting time on tutorials that required sccs) I finally found an [HTML5 pie chart tutorial](https://medium.com/@heyoka/scratch-made-svg-donut-pie-charts-in-html5-2c587e935d72) that is actually helpful.

**Comment by djbpitt** [comment]
@sjw82 Thanks, Sam. See also the “Creating pie charts” section of <http://presidential.obdurodon.org/methodology.xhtml>.
