### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by loreese** [obdurodon/dh_course#358]
I'm struggling with what I believe is a namespace issue on the SVG exam. The error I get when I open the page in my browser is: This page contains the following errors:
error on line 2 at column 1: Document is empty. My declaration appears like so, starting with line 1:

```<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/2000/svg"
    exclude-result-prefixes="xs" version="3.0">
   <xsl:output method="xml" indent="yes"/>
```
To begin I opened a new XSLT doc and added the SVG namespace declaration. 
With this declaration, none of the code I have written will render, despite seeing things rendering in the oxygen output, so any input would be greatly appreciated.

**Comment by djbpitt** [comment]
@loreese There’s nothing wrong with what you write above. When I extend it to:

```xslt
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/2000/svg"
    exclude-result-prefixes="xs" version="3.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <svg><circle cx="0" cy="0" r="100" fill="red"/></svg>
    </xsl:template>
</xsl:stylesheet>
```

and run it, it outputs SVG that I am able to open and view in a browser.

Try saving your output during the transformation, opening it in \<oXygen/\>, and validating it. Perhaps that will tell you where the problem is lurking.

**Comment by loreese** [comment]
@djbpitt  well, that is good news. When I open the output in oxygen, it displays all the values for each pasta. The error I get is on line 2, where the first value is. It reads: content is not allowed in prolog. The first template in my XSLT reads:

```    <xml:template match="/">
        <svg>
            <g transform="translate(40, 500)">
                <line x1="0" y1="0" x2="500" y2="0" stroke="black" stroke-width="2"/>
                <line x1="0" y1="0" x2="0" y2="-100" stroke="black" stroke-width="2"/>  
                <xsl:apply-templates select="//pasta"/>
            </g>
        </svg>
    </xml:template>
```
I'm not sure what content the error is referring to in this case, as this code is directly below my output.

**Comment by djbpitt** [comment]
@loreese “Content not allowed in prolog” usually means that you have some text at the beginning of your document, before the start tag (other than the XML declaration, that is, and that’s optional). When you save the output of the transformation, are you certain that there is nothing before the opening `<svg xmlns="http://www.w3.org/2000/svg">` tag?

**Comment by loreese** [comment]
@djbpitt I cleared it up when I went nuclear and started a new XSLT doc. I have no idea what was causing that error, but things are rendering in the browser now.
