### ISSUE TITLE
XQuery # 3

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#359]
I'm having trouble understanding exactly what do I need to do in this exercise: _"...use **eXide** to develop a query or set of queries to explore the text you’ve chosen, that is, to extract and format something interesting about the text. Your **XQuery** should be more interesting and more sophisticated than just a simple **XPath** to retrieve the value of a single element, but what you find interesting in the text is for you to discover. We would suggest beginning by formulating a question and retrieving the information you need to answer it. Once you’re getting the data you want, try to incorporate your query into a structure that lets you embed the information you’re retrieving inside valid **HTML output**..."_ How can I make an HTML with XQuery? I thought that this software/method was to find stuff inside an XML or a collection of XMLs.

**Comment by djbpitt** [comment]
@ddaud02 The posted solution to XQuery 2 illustrates how to use XQuery to create HTML output. HTML output is optional for XQuery 3, but once you get the hang of how HTML and XQuery nesting works, the rest is just like regular XQuery.

**Comment by ddaud02** [comment]
@djbpitt Thank you, David, I think I'll just ask a series of questions like testing someone. 👍
