### ISSUE TITLE
SVG Question

### ISSUE THREAD

**Issue by khuber116** [obdurodon/dh_course#361]
I'm currently trying to create graphs that show the "open" and "closed" values we tagged in each of the poems we used in our research. Each graph will be the same, but as of now, I think I need to run a transformation for each of the poems individually. Is this correct or is there a more efficient way of going about this?

**Comment by djbpitt** [comment]
@khuber116 You can use the `collection()` function, which we introduced in XQuery, in XSLT, as well, and process an entire directory full of XML documents at once. You can also run a XSLT _batch_ transformation from the command line to apply the same XSLT transformation to multiple input files. If you’d like, set up a time for us to meet to go over those procedures.

**Comment by pickettj** [comment]
If @khuber116 takes @djbpitt up on the offer for a batch processing walk-through, I'd love to sit in...

**Comment by gabikeane** [comment]
Your team member @Guifindor knows how to do this! I mentioned during our Friday meeting that you'd need to collaborate in order to solve this one, so please do so! Matt figured out batch processing all on his own and I'm sure he'd love to teach you.

**Comment by khuber116** [comment]
Matt actually already showed me this but when we discussed it we were talking about making a graph of all poems and I wasn't sure it applied to this as well. Thanks!
