### ISSUE TITLE
Presentation 

### ISSUE THREAD

**Issue by emmamamula** [obdurodon/dh_course#363]
I know that our presentation should focus on all aspects of our project, but should there be more of a focus on the final website itself or the process that got us there?

**Comment by djbpitt** [comment]
@emmamamula Your focus is up to you. With that said, since the audience will include people who are interested in the research but perhaps not in the technology behind the methods (in your case, for example, Ljiljana), I would recommend prioritizing the research questions and results, using the web site to help explain your research.

**Comment by ddaud02** [comment]
@djbpitt we are having problems centering an SVG file that we created. The first picture is how it looks like on our website. The second picture is how it looks in any new/google chrome tab (50%). The third picture is how it is in our XML, inside a **div**. 

<img width="1124" alt="Screen Shot 2019-04-17 at 7 38 03 PM" src="https://user-images.githubusercontent.com/46380238/56327435-5bf78b00-6148-11e9-8fa5-d041248156a2.png">
<img width="505" alt="Screen Shot 2019-04-17 at 7 39 12 PM" src="https://user-images.githubusercontent.com/46380238/56327593-fe177300-6148-11e9-9989-1e5689f7e24f.png">
<img width="1074" alt="Screen Shot 2019-04-17 at 7 41 59 PM" src="https://user-images.githubusercontent.com/46380238/56327596-066fae00-6149-11e9-9850-fec150441596.png">

**Comment by djbpitt** [comment]
@ddaud02 Add `@height` and `@width` attributes to your `<svg>` element, e.g.:

```xml
<svg xmlns="http://www.w3.org/2000/svg" height="700" width="700">
```

**Comment by ddaud02** [comment]
Thank you @djbpitt, it worked perfectly. One of today's presentations had the same issue... I do not remember which one. 
<img width="1238" alt="Screen Shot 2019-04-17 at 7 52 51 PM" src="https://user-images.githubusercontent.com/46380238/56327892-6d419700-614a-11e9-8b81-51c52b082f0e.png">
