### ISSUE TITLE
SSH Secure File Transfer "Permission Denied" Error

### ISSUE THREAD

**Issue by Nerdologist** [obdurodon/dh_course#364]
In SSH Secure File Transfer, I sometimes get an error when I try to replace an html file already on our project site.

![image](https://user-images.githubusercontent.com/46368238/56301433-ccc98380-6105-11e9-9ae3-596a75307680.png)

The above does not say what specific error was encountered, of course. I was not able to get a screenshot of the specific error message, but if memory serves, the error discussed at the following link is the same one I encountered:
https://answers.ssh.com/questions/1244/file-transfer-failure

What can I do about this? (Oddly enough, the transfers seem to succeed despite the errors, but I would rather not run into these error messages so often.)

Edit: Here is the exact error message I get:

![image](https://user-images.githubusercontent.com/46368238/56305209-d0f99f00-610d-11e9-8476-67b7ae169030.png)

**Comment by djbpitt** [comment]
@Nerdologist We’ve seen this error message as well. Apparently although all team members should have write access to the directory space (which means that you should be able to overwrite files that your teammates uploaded), sometimes the system will refuse to overwrite a file that doesn’t belong to you (that is, that you didn’t upload yourself). What surprises us is that when we’ve seen that behavior in the the past, the system *does* let you delete the old file separately first and then upload a new one.  I’m not sure why you have to work around the upload with that two-step process, but as long as the work-around ... er ... works, I’d suggest just going with it.
