### ISSUE TITLE
Incorporating SVG into pages?

### ISSUE THREAD

**Issue by loreese** [obdurodon/dh_course#365]
I have my XSL file that renders my SVG bar graph, but now I'm unsure how to incorporate that into my actual XHTML page. Since I refer to elements in our text file, it renders an error message that tells me my text element in the templates is unbound. Do I need to reference the text file, and if so, how can I do this?

**Comment by zme1** [comment]
@loreese There are a handful of different ways to do it. I will push the XSLT file that shows one strategy momentarily. Long story short, we can transform our graph into a snippet of XHTML code, write it into an SSI file, and render it just like we do with our navigation bars. Would you have time to meet for a couple minutes before the presentations begin so we can review it more in-person? I'll also attach some comments to the changes for your reference in the meantime.

**Comment by loreese** [comment]
@zme1 Excellent, I'll look those over in a bit. I have time before the presentation to go over things so that would be great. I'll be on campus pretty early if you have time during your usual Friday office hours.
