### ISSUE TITLE
Farewell 

### ISSUE THREAD

**Issue by ddaud02** [obdurodon/dh_course#367]
Our group **Yugoslav-Folklore** (@emmamamula, @ddaud02, and @MLuckman ) has finished the website it has been a pleasure to share with you this semester. Go to our site [http://dh.obdurodon.org/course-projects.xhtml](url)  and give us your opinion about. Have a good summer.

![bucket](https://user-images.githubusercontent.com/46380238/56843097-b2607a00-686a-11e9-9de7-7e3217e4ee9f.png)

**Comment by djbpitt** [comment]
@ddaud02 @emmamamula @MLuckman Thank you all for your good work on an exciting and thought-provoking project, and best wishes to you all in the future, both your DH-inflected future and in general!
