### ISSUE TITLE
Can't Attach XPath 3 to GitHub submission

### ISSUE THREAD

**Issue by JosephDRogers23** [obdurodon/dh_course#37]
When I tried to submit my Xpath 3 text file as an attachment, CourseWeb gave a message saying that my file is a possible security threat and could not be attached. (I'm guessing that one of my queries set off a flag, but I'm not sure which one it is.) The only other recommended solution than fixing it is to attach it as a zip file - is this what I should do?

**Comment by gabikeane** [comment]
You can zip it, that's fine with us! It will also make its way to our grading folder if you email it to me.  A text file attachment shouldn't throw any red flags (I hope).
