### ISSUE TITLE
practice post

### ISSUE THREAD

**Issue by crissyshan** [obdurodon/dh_course#374]
a new issue.

**Comment by crissyshan** [comment]
# I have a question.

* Why would we want to use markdown if the typing box already supports bold/italics/numbering in a point-n-click format?
    * How come there's no way of easily using tab to indent in the box? 

As Dr. Pickett said:
> "This course is scaffolded."

**Comment by pickettj** [comment]
This is a good question! The typing box "supports" bold/italics in the sense that clicking on it (or ⌃i) automatically enters the Markdown for you. But not all Markdown necessarily do this, so it's helpful to know the Markdown code itself.
