### ISSUE TITLE
Project Proposal: Van Gogh as a "Tortured Genius"

### ISSUE THREAD

**Issue by charlietaylor98** [obdurodon/dh_course#388]
The mythos surrounding Vincent van Gogh’s tragic life and death is as pervasive in the public consciousness as the artist’s actual work. Van Gogh the Painter has become synonymous with Van Gogh the *Fou*, and his consumption of yellow paint, his gifting his ear to a prostitute, and his ultimate suicide in Overs-sur-Oise all contribute to a convenient portrait of Van Gogh as a tortured genius. Wrapped up in this portrait is a broader notion that mental anguish leads to creativity, and that to be a great artist is to suffer.

But was Van Gogh actually most productive as an artist during those moments of suffering? Through his letters, over 800 of which survive and are available through the [Van Gogh Letters Project](http://vangoghletters.org/vg/about_1.html), I hope to get a better sense of when the artist was battling with mental illness and when he was in a period of recovery, as well as when he was producing high volumes of artwork. (The latter can be gleamed from Artstor’s collection of paintings and drawings, but [Artstor](https://library.artstor.org/#/search/van%20gogh;page=1;size=48) largely only gives the year of the work, whereas when the act of painting is mentioned in a letter, exact dates can be determined more definitively.) The markup will likely include explicit mentions of mental illness and/or recovery (phrases like “*en pleine fièvre et faiblesse relative*”/ “in the middle of relative weakness and fever”), as well as mentions of hospitals and doctors. Stress factors such as financial burden and deteriorating friendships will also be marked up alongside “un-stress” factors like critical success. Finally, Van Gogh frequently mentions work, especially in correspondence with his brother and life-long supporter, Theo; these mentions will be marked up and used to determine if periods of either mental illness or mental wellness correspond to periods of productivity.

Considering the brothers’ intimacy and the sheer volume of letters sent to Theo alone, if a markup of all documents proves cumbersome, I think I can limit my research to only correspondences with Theo and still get a good understanding of Vincent’s life at any given moment.

**Comment by djbpitt** [comment]
@charlietaylor98 The XML for the Van Gogh Letters project is available from a link at the bottom of http://vangoghletters.org/vg/about_6.html#intro.VI.6.4.. If the markup looks useful for your research, it means that even if you decide that you need to add markup (for example, if their markup doesn’t tag for medical issues but yours needs to), you won't have to mark up raw text from scratch.
