### ISSUE TITLE
Project comment problem

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#39]
Did the magic realism page disappear?  I get an error page when I click the link.

**Comment by djbpitt** [comment]
@mtm80 @rmb165 The repo has been made private, which means that is accessible only to those who have been given permission. Rachel will give permission to all members of the course, which will make the error go away.

**Comment by mtm80** [comment]
The page is still inaccessible.   Should it have been open by now?

**Comment by zme1** [comment]
@mtm80 Yes, @rmb165 can you be able to send invitations to all the other students to be collaborators on the repository this evening?

**Comment by brucknerp** [comment]
I never received an invitation so I still can't access their page.
