### ISSUE TITLE
Project Proposal: High Variety Vs Low Variety of Arabic

### ISSUE THREAD

**Issue by Islam-M-Farag** [obdurodon/dh_course#394]
As Ferguson (1959) argued that Arabic language is one of the fewest languages that suffer from the issue of **diglossia**, in which a Low variety *Ammiya* and High variety *Fusha*  of Arabic used and coexist together.  Although the artificial harmonious relationship between the two varieties, these varieties are almost rivals: currently, low variety *Ammiya* is trying to __take over__ the fields traditionally and previously dominated by Fusha such as religious speeches, media talks, literary works (e.g., poetry, short stories, etc). This conflict is highly evident when teaching Arabic as a foreign or second language where both teachers and students get puzzled and confused easily of what _dialect_ to teach: in what context a specific variety is appropriate and when it is suitable to be used. It was suggested teachers may teach  one variety only, two varieties simultaneously, or the middle variety which does not have a solid foundation of what it really is (Al-Batal 1992).```Despite these differences argued by researchers; __to date__, there is not any  **systematic approach** used to study big data to distinguish between the two varieties or examine how low variety is different from high variety in terms of vocabulary, grammar, etc.``` With the use of digital humanities, the current proposal tries to answer the following questions:
   1. How far is the difference between Egyptian dialect (low variety) and Fusha (high variety) in terms of verbs and nouns?  

Using XML as the tool, the researchers will do textual analysis of  20 poems written by *AbdelRahman Abdnudi* in Ammyia variety. The analysis of these poems would help answer the the following subset questions:

     1.	How many verbs and nouns are completely different from their Fusha counterparts?
     2.	How many verbs and nouns are similar or derived from their Fusha counterparts?
     3.	How do the difference and similarity influence the judgement of the two varieties and their use?

The answers the researcher get should give more robust and accurate assumptions about the relationship between *low variety* and *high variety*, and whether there is a middle dialect between them or the two varieties are completely two different sets.

**Comment by ebeshero** [comment]
You've probably been discussing this with your instructors already, but in case not, there will be some exciting challenges with encoding right-to-left languages in left-to-right XML markup! Read more about it: http://www.i18nguy.com/markup/right-to-left.html There's a workshop scheduled at the Digital Humanities Summer Institute at U. Victoria on the subject: see https://dhsi.org/affiliated-events/ .  I attended part of it last summer--you'd likely find it very interesting and have much to contribute!

**Comment by Islam-M-Farag** [comment]
Thank you for the info.
