### ISSUE TITLE
Project Proposal: Translations of Vergil's Aeneid

### ISSUE THREAD

**Issue by marionbriley** [obdurodon/dh_course#395]
### Translations of Vergil's Aeneid
I am interested in studying the (in)accuracies that come with translations of Vergil's *Aeneid* into other languages. No two languages are the same, hence no two languages should ever directly line up to produce exact translations. I would like to investigate where elements of the storytelling diverge due to different characteristics of each language, or different choices of each translator. To summarize: **in what ways do these translations succeed at translating _The Aeneid_ honestly and accurately, and in what ways do they fall short?**

I am not sure whether it would be more interesting to look at a variety of languages, or at a variety of translations in one language for different purposes (commercial reading for people knowing only the language, or academic reading for those trying to understand the original text). Perhaps both could be done; and this could be similar to the Galician-Portuguese lyric website, only comparing selected translations at a time. I myself am comfortable with English, Latin, and Spanish, but if we could expand to even more languages with unique structures (perhaps an Asian or Slavic language, or another case-based language like German), this would further enhance the project.

Changes could be tracked through careful markup of grammatical and semantic content of the text–where structures change and meanings differ between languages. As a final project, annotations or commentary on the text could be organized similarly to the “My Immortal” site. However, if we want to tag almost every word, this would become a massive endeavor. It would likely be more prudent to either focus on one book of the Aeneid, or perhaps on several iconic excerpts, such as Laocoon and the snakes, Dido's suicide, and Aeneas and Anchises’ escape from the burning city of Troy. Some elements I think it would be interesting to focus on:
* Tense *(Some languages have ways of representing tenses that others do not. How does the translation communicate tense? Is it authentic to the original tense?)*
* Figurative language *(Can metaphors or similes be translated? How does the translation handle sound devices?)*
* Names *(In Latin, one character may be referred to by many different names. How are these translated?)*
* Overall word count *(This probably is more of a "statistics page" type item, but this says a lot about the differences between languages!)*

**Comment by sjw82** [comment]
@marionbriley Excellent proposal! I love your idea and it is very well thought out. Including word count in your examination is, in my opinion, a great idea. Just a few things you might want to think about before diving in:
1. What translations can you use that aren't copyrighted? Modern translations typically are, so start to think about what sources you could use.
2. You present two very interesting, very different approaches to this project in comparing within one language versus comparing between languages. Many factors will influence which you decide to do, not the least of which will likely be practical constraints such as how your team members are able to contribute i.e. what languages they're comfortable with, what translations you can get your hands on, the pace you're able to keep, etc. But also consider what audience you want to serve. That will influence both your research question and your design choices, so it is important to keep clear in your mind.
3. You're right to consider the scale you'll be able to operate on—limiting your research focus is a great idea. It is important to keep in mind when choosing excerpts, if you go that route, what criteria you're basing the selection off of. Are they the excerpts most frequently referenced by modern scholars? The book translated into the most languages? The story cited by the most scholars/storytellers of the time?

Overall, it looks like you have a very clear idea of what you might do. Good luck!
