### ISSUE TITLE
Project Proposal -  Songs of Colonization 

### ISSUE THREAD

**Issue by mblynn** [obdurodon/dh_course#396]
Maja Lynn
1.23.20
Project proposal
GER 1550

### Songs of Colonization

Songs are often a reflection of the cultures and people who create them. Through lyrical analysis, it is possible to draw out themes and patterns that relate to broader historical contexts. A song is a direct link the feelings and attitudes of the person who created it and offers a unique lens into the past. Through the use of XML technology, I want to analyze how language and motifs used in the songs sung by colonizers are evocative of the violence and romantic nationalism upheld by colonial powers. I have found three examples of songs from German South West Africa, present day Namibia: “Südwesterlied”, “Afrikanisches Reiterlied” and one unidentified song from the book *Deutsches Südwest Afrika*. Namibia under colonial rule presents a particularly interesting example because it was the aggressive expansion of colonial soldiers that led to a genocide of two of the largest cultural groups in Namibia, the Herero and Nama, from 1904-1907. These songs show both how the soldiers romanticized the landscape, referring to it as their “homeland”, as well as their derogatory descriptions of the people they abused. 

> The kudu and the wildbeest, the gemsbok and the ostrich, I shoo them out of the rift and shoot them for a feast. Among the Hottentot, Hereros, I find a thousand women and yet I only long to be with my sweetheart
> 
> Through mountain and valley, up and down; I ride away and away; up and down in step and trot; from place to place; even the gallop I don’t avoid; free is [die Pas] in front of me; yet only when the homeland is in sight, will I stop

Much of the imagery is reflective of a fascination with the “wild west” in the United States which demonstrates the connections of German colonization and genocide in Namibia with global trends of westward expansion and imperialism. All of these songs are from German Southwest Africa, but it would be possible to diversify and examine colonial songs from other colonies in Africa, or even from around the world in order to draw comparisons. For example, one could compare songs from the British and German colonists in Africa, or compare songs written in the American west with the songs from German colonizers. Through this method, we could examine their worldview and how it influenced their treatment of the people that they “conquered”.

**Comment by ebeshero** [comment]
Could you comment more on (and perhaps link to) sources for the colonial song lyrics? For this class, given all the technical skills you will be developing, it will be helpful if your song lyrics are readily available in one or more digital resources!

**Comment by mblynn** [comment]
Two of the songs that I referenced in this proposal I only found in a book, however they are not too long to type up. The other song can be found here: [http://ingeb.org/Lieder/hartwiek.html]
