### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by JosephDRogers23** [obdurodon/dh_course#40]
What's the one thing that you've found most significant (so far) in an example website that you want to incorporate into your project site? For me I think it's been any site with a map feature (ORBIS, the GIS lecture). I don't know how detailed it would be within the scope of this course but I love maps and I think it would be pretty cool to incorporate that into our project site on Magic Realism, possibly to show the locations of some of the allusions that we're marking up.

**Comment by brucknerp** [comment]
The map features on sites are definitely cool, but for me and for our project's scope I liked representations of topic modeling the best--it takes a bit of creativity to create a neat visualization of data, but if your group or any group takes up the challenge, I'd love to see the results!
