### ISSUE TITLE
Project Proposal: Soviet Rock Songs in Estonia & Leningrad 

### ISSUE THREAD

**Issue by crissyshan** [obdurodon/dh_course#402]
The proposed project will examine the text of rock songs from the Soviet Union, focusing on the time period from 1970 to 1991 and the geographical areas of Leningrad and Estonia. Songs from Leningrad will be analyzed in the original Russian text, and sourced from the internet. Songs from Estonia will be analyzed in translation, and sourced primarily from the book  _The Power of Song_ by Guntis Smidchens, as well as from the internet where necessary. 
The purpose of this project is to code and quantify the positive and negative valences of particular song lyrics from different eras and locations, as well as to quantify the degree of “dissident”-ness within the text in order to better understand whether rock music, which became politicized after government attempts to curb and ban it in the Soviet Union, truly had a political and oppositionist content. What kind of political content was this? How and why do we note this to be political content? How does it correspond to our understanding of the rules the Soviet culture abided by? Aside from examining the “dissident”-ness of these works, this project will also look for political content by quantifying nationalist tones as well as “Soviet”-ness in song lyrics based on different reference attributes. Examples of some attributes include: nature/resources, heroes, labor, technology, communication, unity, nation, all-Union, progress, etc. The outcome of this quantification and examination will be a better understanding of what constituted rock music in different areas in the Soviet Union. By showing that the rock music movement had different content and culture depending on geographic area, but that each area in the Soviet Union nonetheless had one of these movements, this project will contribute to a growing understanding of the Soviet Union as simultaneously united and heterogeneous.

**Comment by MLuckman** [comment]
You're going to have some issues here with copyright. The song lyrics themselves are probably under some level of copyright, although you might be able to use them anyway (I'm not a lawyer, but we sometimes have leeway with lyrics). However, the translation in the book, published 2014, absolutely are copyrighted and you wouldn't be able to use them. I advise looking into earlier topic (where everything ends up in the public domain due to age) or if looking at something modern, pick something that's explicitly open-source.

**Comment by ebeshero** [comment]
Obdurodon projects have sometimes investigated music lyrics available from web sources, and rarely have they caused issues, though @djbpitt can say more about the Russian Rap project which provoked a take-down notice recently from the Russian government(!) I don't think that was at all to do with copyright, but rather with an attempt to suppress. But for a related example, take a look at the [Turkish Rock project](http://turkish.obdurodon.org/methodology.html), which seems to have sourced its lyrics from the wilds of the internet.
