### ISSUE TITLE
Project Proposal - Characters and Motifs of Shakespeare

### ISSUE THREAD

**Issue by knc47** [obdurodon/dh_course#404]
Kalan McDonald
Computational Methods in the Humanities – Project Proposal
January 24, 2020

One particular idea that I would be interested in pursuing as a project would be to analyze and simplify the process of observing the characters and themes of Shakespeare throughout his plays. In other words, I would be looking to create an interactive quasi-encyclopedia of Shakespearean works. The intention would be that one might be able to read through various plays and simply gain an improved insight into the roles of the cast of characters, which can be broad and confusing. However, if one wanted to observe deeper information, it would also be made available to explore various motifs utilized by Shakespeare and their origins in folklore or fairy tales in 17th century culture. In addition, Shakespeare himself was a student of classics, and was thus noticeably educated in both the Roman and Greek legendarium. I would incorporate his references to such as well.

Such a project would also incorporate influences from Shakespeare’s personal life. It would also allow users to see other occurrences of similar motifs within separate plays. Truly, this would just be a platform to bring together the information available to more comprehensibly study Shakespeare’s work and influences. With such information, one would be better able to perceive the intentions of the works, and better able to comprehend and interact with the culture and society that produced them. For it is often difficult for students of Shakespeare to disengage with the cultural influences of their own time in order to critically examine that of the 17th century. I would hope to aid that process with this project.

**Comment by MLuckman** [comment]
In this course, we focus on projects with a research question. This looks ambitious and very helpful, but make sure it has a research question that it tries to answer. You can mark up the entire corpus with information that'll help other scholars, and they'll thank you, but make sure you have your research question in mind.

**Comment by ebeshero** [comment]
There's a very long ongoing project called the New Shakespeare Variorum that began way back in the 1990s as a mostly print project and is taking on a new digital life at Texas A&M this year, and you can read about it at http://codhr.dh.tamu.edu/2019/11/13/digital-future-for-new-variorum-edition-of-shakespeare-to-be-with-codhr/ . I mention this not to say your idea is being "taken" by a giant, funded project team, but rather to say, what you are describing is a very massive project indeed, not one that could be completed inside a spring semester. So, how could you narrow this and give it a concentrated research question? Which is your favorite Shakespeare play? Take a moment to review it and think of what kind of research questions you might investigate using XML markup and a good schema...

**Comment by ebeshero** [comment]
There's also no reason you couldn't do work on a cluster of Shakespeare's plays, or even the entire corpus, as simple marked up versions of the plays do exist--and you'll probably be exploring them in the XPath and XQuery units in this course. But you'd want to concentrate on some phenomenon you can track readily with the tools you'll be learning in the course. Perhaps all the references to classical deities across the corpus?
