### ISSUE TITLE
Emily Dickinson Project Proposal

### ISSUE THREAD

**Issue by rasaula** [obdurodon/dh_course#405]
### The Quieter History of Emily Dickinson ### 
Emily Dickinson is arguably one of the most reclusive literary icons in recent history (which is saying quite a lot). It's often thought she fostered a life-long longing for some unnamed man referenced in written notes, whom she called "The Master," despite no evidence of a romantic or platonic relationship with this mystery man. Beyond this speculation, most or all accounts find Dickinson was a recluse for the majority of her life, credited to the amount of her loved ones who died during a very short timeline. She remained unmarried throughout her life, and became known as a bit of a creepy spinster. 
Of course, there are narratives that work to define this image, and I've always found them incredibly interesting. Susan Gilbert, who eventually became Dickinson's sister-in-law after marrying her brother, was and is rumored to be Dickinson's lover. Before and after Gilbert married Dickinson's brother, there is reason to believe the two women were lovers for years. In many accounts of Dickinson's life, however, Gilbert is completely ignored as a possible love interest, and in fact has often been completely erased from Dickinson's narrative.
Of course, determining what the two women truly meant to each other during their lifetime is impossible to do by any means, but by examining their direct correspondence, I hope to give the attention to their relationship, be it romantic or platonic, that has so often been ignored. 
This project would include analyzing letters between the two of them along with Dickinson's poems, as a good number of them seem to be directed toward a woman. I imagine the nature of what would eventually be marked up would change as the project grew, but as of now I imagine all mentions of Sue or an unnamed woman in Dickinson's poems would deserve a markup, and mention of the two's relationships in letters would be included in markups as well.

**Comment by sjw82** [comment]
@rasaula This is such an interesting proposal! Just to flesh it out a little more I have a few questions.
1. Do you intend to also look for references to "The Master" in the letters and poems or just Gilbert? Comparing the two might possibly show a shift over time—perhaps as she wrote more about an unnamed woman, she began to write less about The Master. I don't know a thing about it, so I can't even claim that that is a hypothesis, but it is something you might look for.
2. Consider how you're going to handle the data from the poems vs. the correspondance. Obviously the markup will differ to a degree, but the significance of the data also changes because the intention behind it changes. You don't need to have an answer yet, but think about how you will account for intention.
3. Do you know what source you're going to collect the letters and poems from? Are you sure that they're digitized in a machine readable way (being OCR readable rather than being photographs)? If so, you might link them in a comment to help your peers visualize your project. If not, how will you find them and, if necessary, make them usable for Oxygen?

**Comment by ebeshero** [comment]
There are several good sources for Dickinson's writings available now that would support a project like this. For the Greensburg campus newtfire project on Emily Dickinson (see https://dickinson.newtfire.org), our students found the Emily Dickinson Archive (https://www.edickinson.org/) especially helpful for its store of digital manuscripts, and I remember that their developers were helpful when our students needed to contact them about a missing image for an MS of a poem.

One thing you may be aware of is that Dickinson wrote her poems in multiple versions, sometimes changing the gender of her pronouns, as in this case from Fascicle 16: http://dickinson.newtfire.org/16/1611.html  (Click on the pink button showing the different version she wrote in her Letter to Susan Dickinson): That image is one that I think our team requested from Dickinson Archive editors. Retrieving material to work with on this project was a bit laborious, and it might be helpful for you to review their project methodology where they describe their source materials: https://dickinson.newtfire.org/methodology.html  

I think you can carefully dig up a pile of good base texts to work with for encoding from the [Emily Dickinson Archive](https://www.edickinson.org/), but I'm not it will be so easy to find Dickinson's letters in an uncensored state available in digital format. I'm not entirely sure of this, but I think what's available are digitized images of Mabel Loomis Todd's edition, which are almost certainly just a bit censored due her Todd's er, close proximity to Emily's brother Austin Dickinson. (For more on that steamy saga, here's a fun article: https://www.newenglandhistoricalsociety.com/mabel-loomis-todd-adulteress-made-emily-dickinson-famous/ ). Anyway, *be careful* with 19th-century editions of authors' letters, as the editors were often careful to cut out and alter what they considered "delicate" material.

**Comment by ebeshero** [comment]
By the way, hi! I'm the professor of the "sibling DH course" at Pitt-Greensburg, and @djbpitt and I tend to check in on each other's course GitHub repos from time to time. :-)

**Comment by djbpitt** [comment]
@ebeshero Thank you!

**Comment by ebeshero** [comment]
For anyone following, I've left some updated comments above. There's a great ongoing digital project on Emily Dickinson's correspondence which, even though under construction, contains lots of interesting material that is readily paired with poems. And like the material in the Emily Dickinson Archive, you can work with digital representations of the texts and pull them together in your own markup without having to do too much reading of manuscripts in photo facsimile (unless of course you want to do that--as our students did!) :-)
