### ISSUE TITLE
Project Proposal - Grimm's Fairy Tales

### ISSUE THREAD

**Issue by KirstenRehnea** [obdurodon/dh_course#406]
Kirsten Hall

# *Grimm's Fairy tales*
The *Grimm Fairy Tales* are a collection of household tales told in Germany. They are not as sweet and lively as a typical fairy tales, but rather they are more dark. They were created published between 1812 and 1858. Some tales that we all know, such as Cinderella, are an adaptation on  Grimm's fairy tales. 
This project has two main goals. The first goal is to break down both the English and the German translations of the tales and examine the elements of Gothic style literature. Looking at how they differ in the two translations. These include:
* Gloomy, decaying setting
     * Haunted houses, castles, mazes, secret passages. 
* Supernatural beings. Along with monsters, vampires, zombies.
* Curses and Prophecies
* Damsels in distress
* Heroes
* Romance
* Intense emotion, madness.
This goal is intended to look at how elements of the Gothic are used in the tales, and how these elements might have been changed in translation. Looking at how the German compared to the English express these Gothic elements. 

The second goal of this project is to look at the original tale and compare it to adaptation that exist. Questions that this goal is aimed to cover.
* How have the tales been changed? 
     * What elements were changed?
* Does it change the moral of the tale?

**Comment by ebeshero** [comment]
This project would need to locate some existing digital editions of Grimm in German and in English.  I'm not as familiar with this as aI am with the Emily Dickinson materials (see https://github.com/obdurodon/dh_course/issues/405), but my recommendations are similar: To do this work, you need some base texts to start with. What are they?
