### ISSUE TITLE
GitHub for project management webpage is not working

### ISSUE THREAD

**Issue by Islam-M-Farag** [obdurodon/dh_course#408]
This webpage is out of service, I guess. I receive this message whenever I click on it "404 not found."

**Comment by sjw82** [comment]
@Islam-M-Farag sorry to hear you're having this issue! Which webpage are you referring to? Can you attach a link?

**Comment by marionbriley** [comment]
@sjw82 I believe it is this one: https://dh.obdurodon.org/projects_tab_2184.xhtml because I also received an error message that it was not found on the server when I click on the link in the syllabus.

**Comment by sjw82** [comment]
@Islam-M-Farag @marionbriley 
I think this [this](https://dh.obdurodon.org/projects_tab.xhtml) may be the page you're looking for. Let me know if it isn't

**Comment by Islam-M-Farag** [comment]
Yes, this is the one. Thank you

**Comment by djbpitt** [comment]
Sorry! We moved the page to <http://dh.obdurodon.org/projects_tab.xhtml> and I missed the link on the syllabus when updating. It’s fixed (on the syllabus) now.
