### ISSUE TITLE
Single-Issue Post: Command Line and Github

### ISSUE THREAD

**Issue by dap167** [obdurodon/dh_course#417]
My understanding of the command line remains the same, but that's because I'm already very used to using it. On the other hand, I feel that my comprehension of Git is stronger now, since we're using only the command line to access Github and save our workflow where I worked in Desktop before.

One thing that has changed is the addition of `git add` to put changes inside the staging area before being committed. As far as I know, this step is virtually non-existent in Desktop. I am very much used to just programming and hitting commit before pushing the new changes to the branch (and hopefully not need to pull beforehand).

I want to say that operating multiple branches would be useful for the project, but I'm thinking that there isn't much point. It doesn't seem like that layer of separation and extra management is necessary for the project as a whole. It's not like we're working on separate features that need to be reviewed.

**Comment by djbpitt** [comment]
A lot of small project teams just commit everything to the master branch, and that simplicity has advantages. Even in a small team, though, there may also be advantages to branches, pull requests, and code review. I wouldn’t suggest starting there until you’re familiar with the basics, but when you’re ready to explore something new, see https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
