### ISSUE TITLE
Discussion Post: Git and GitHub

### ISSUE THREAD

**Issue by EsRessel** [obdurodon/dh_course#418]
Since my first experience with the Git, I feel a bit more confident with the system, though I will still need to reference guides for small tasks. I am now able to read and understand most of the printed lines on the terminal. I was able to successfully clone the repo, yet I haven't made pull requests or committed any materials. Also, in our first project meeting, our mentor reviewed the ways to avoid drastic errors, such as deleting our entire repo. After getting into the groove of project development, I'm sure I will become much more comfortable with the platform. Additional exposure through SSH has also increased my confidence in using the command line. 

In terms of GitHub, I feel like I have a pretty good grasp of the functions and am able to speedily navigate between the different sections. After creating and responding to issues using markdown, I am comfortable with the basics of the markdown language and feel that I can write fewer references to the guide. The issues section will be useful for the project team. It allows us to give updates and share materials. For example, when doing background research I came across a resource that would be useful for our group, so I created an issue and included a link to the resource. A feature that I want to learn more about would be forking. I see it at the top of the repo, yet don't completely understand its function and effect on the repo and its contents.

**Comment by djbpitt** [comment]
Forking isn’t typically used much within a small project team, but if you’d like to start moving beyond the basics, we can recommend reading up on branches. See https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
