### ISSUE TITLE
Reflection on GitHub

### ISSUE THREAD

**Issue by blueciren** [obdurodon/dh_course#419]
I have never worked on this type of collaborative platform, including not even Google Docs. So most of the features are new and challenging for me. But the features that allow collaborators to track all the changes and download all by "git pull"  sound convenient and useful, even though I have very limited experiences so far. 
One issue I had when I was uploading my last assignment was I fell into the trap that did not allow me to return to the previous page in git bash while trying to git push. The professor Birnbaum suggested me to change the default editor from vim to nano, which resolved the problem. As a beginner, I am gradually learning how to use the platform.

**Comment by djbpitt** [comment]
The default editor for Git is *vim*, which is very capable, but not friendly to new users. If you like the challenge, it’s worth looking up a tutorial and starting to learn it. But in terms of just getting your work done in Git, switching to *nano* is a simpler and fully adequate option.
