### ISSUE TITLE
Single Issue Post: Michael Barth

### ISSUE THREAD

**Issue by mjyb16** [obdurodon/dh_course#420]
Having worked in the command line for a while now and having toyed with using GitHub, I was already familiar with much of this software. However, I had not used GitHub for its true intended purpose, collaborative version control, very much up until now; I was mostly using it to store and share software online. This class has thus far taken my knowledge of Git to the next level, introducing me to the formal workflow of pulling, adding, committing, and pushing. 

The ability to create issues and project to-dos will be incredibly useful for working effectively as a team, and we will continue to use them to split the workload fairly between team members by assigning specific tasks. The project board also allows us to communicate when we have started and finished a task by dragging the task card to the in-progress and done sections. 

I am still unsure about what will occur when we run into a merge conflict, which will inevitably happen; it is when considering this possibility that I sometimes wish for the equivalent of Google Docs (as mentioned in another post) for IDEs, though I understand the dangers this could create as well since edits in the cloud can become more difficult to track compared to local edits that are pushed to the cloud. I would also like to learn more about the wiki, actions, and branching and how we could use them to our advantage when working on this project. The forking concept is also interesting, although probably less useful for this class.

**Comment by djbpitt** [comment]
Merge conflicts do happen, but you can reduce the likelihood by pulling and pushing frequently. There’s a link on our main course page to a resource that describes how to resolve them. Feel free to ask us to walk you through the process if, after reading that, it’s still unclear.
