### ISSUE TITLE
Discussion post: Git

### ISSUE THREAD

**Issue by charlietaylor98** [obdurodon/dh_course#422]
Since my first encounter with the command line, using it has become less intimidating. Trying to get a project up and running that involves a lot of moving parts, I can see the importance of different people being able to work separately and smoothly merge their work into one file. I'm still trying to get a grasp on when it's appropriate to do certain things in Git, ie when to stash to the working directory and when to commit, but I'll be able to best learn those things once I get more practical experience. On Github, I'd like to know more about managing branches; since our corpus is pretty large it would benefit us to work from multiple branches to avoid error as best as possible.

**Comment by djbpitt** [comment]
Branches are common in what is sometimes (vaguely) called the *Git workflow*. There are a few different strategies for using branches to manage development, and this is a good topic to discuss in a project meeting.
