### ISSUE TITLE
Single Issue Post: Command Line and Github

### ISSUE THREAD

**Issue by marionbriley** [obdurodon/dh_course#423]
These are both still steep learning curves for me, especially Command Line. In all honesty, I'm completely terrified of it because I feel like I won't realize if I make a mistake until it is too late or extremely difficult to fix. There are a lot of commands I'm realizing I will have to memorize in order to work efficiently, and it's daunting. It is in no way easy to read and comprehend. However, I know this technology will become easier with time and practice, and I am eager to see myself improve with it.

On the other hand, I feel like I understand Github so far. In fact, I think I am a little overenthusiastic about it. I keep testing out different features and editing things just for the sake of practicing, so our project (Aeneid Translations) has a bunch of commits although only about two or three of them were purposeful and significant. I am particularly interested in the to-do list feature, as I feel like this will be really useful for keeping us organized and on track as each group member works on different bits of the project. Other than that, I feel like I need to explore more to know what is out there. I am sure I will be excited to try out new features and incorporate them into the project as I discover them.

**Comment by djbpitt** [comment]
You’ll get comfortable pretty quickly with the Git commands you’ll use often, such as `add`, `commit`, `push`, `pull`, `status`. We also have to look up how to do the less common things when the need arises, but feel free to ask for help if you get stuck.
