### ISSUE TITLE
GitHub Reflection Post

### ISSUE THREAD

**Issue by Rober-Igtm** [obdurodon/dh_course#424]
Having gotten some hands-on experience with it at our first group meeting, I am feeling a little more confident in my GitHub skills. I understand the process for how to pull, commit, and push files (and the code to do these), but I still need much more practice to fully grasp and master the system. I believe that as our website continues to move further, I will certainly discover new options available through the system and gain better knowledge on how to operate Git. I admit I'm rather anxious about Git at the moment. I have never used any public coding system like this before in my life. But I am hopeful that things will begin to improve. 

One issue I'm particularly interested in is the kanban system. I agreed to manage my group's kanban, and its system for managing what we need to get done and when is incredibly helpful. With pacing ourselves and knowing when and what needs to get done, it will certainly make our long-term plans easy to visualize. As soon as we have a concrete direction for the website, I want to organize and structure our goals in the kanban as much as possible.

**Comment by djbpitt** [comment]
We were all Git beginners once. You’ll become comfortable quickly with the commands we use often (`add`, `commit`, `push`, `pull`, `status`), and with the others you’ll probably do what I do: look them up to remind yourself of how they work when you need them.
