### ISSUE TITLE
Discussion Post 1 

### ISSUE THREAD

**Issue by mblynn** [obdurodon/dh_course#429]
A lot of us seem to be concerned about translations and whether they benefit accessibility or not. When going through my texts, I realized that translations, especially when it comes to song lyrics, may present very complex issues with misinterpretation. However, I still think it would help make whatever work we do more accessible, especially in the Songs of Colonization, which uses English speaking material. Is there a way to put English translations directly under lines of German lyrics? Maybe in a smaller size or different color?

**Comment by djbpitt** [comment]
You can lay out an interlinear translation as an HTML table, and adjust the size and color with CSS? Feel free to experiment with that as your HTML/CSS assignment #2.

**Comment by pickettj** [comment]
Translation is an issue I'm working through for some of my own research as well, @mblynn ; by no means have I answered all or even most of the practical questions that come with coding translation, but I will be interested to see how you develop your project!
