### ISSUE TITLE
XSLT 1

### ISSUE THREAD

**Issue by danakaufhold** [obdurodon/dh_course#44]
I know that it's not likely that anyone else is still up, but I'm having a lot of trouble with the first XSLT assignment and thought I'd ask just in case. I've been working on this for a long time and I still can't understand why my XSLT is finding absolutely nothing. 

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.w3.org/1999/xhtml"
    exclude-result-prefixes="xs"
    version="2.0">
    <xsl:output method="xml" indent="yes" doctype-system="about:legacy-compat"/>
    <xsl:template match="/">
        <html>
            <head>
                Hamlet
            </head>
            <body>
                <h1>Hamlet</h1>
                <xsl:apply-templates />
            </body>
        </html>
    </xsl:template>
    <xsl:template match="head">
        <ul>
            <li><xsl:apply-templates select="head"/></li>
        </ul>
    </xsl:template>
</xsl:stylesheet>
```

This of course isn't meant to be the final version, as it doesn't try to include scene titles or anything, but I can't move forward from here because all it gives me when I run it is the entire text of the play as a huge block. Absolutely nothing is in a list, even though I have the `<ul>` element and a `<li>` inside it. I tried making the template match "div" as well, in case it needed to be a parent (like we did with the titles of the fables earlier), but that didn't work either. I tried basing most of this off of the fables XSLT, since I did save that so I could have reference later, but it wasn't helpful. Does anyone have any idea where I'm going wrong here? I'm wondering if I have to be more specific, but also how I would do that since the tags for the acts and the scenes are the same.

**Comment by djbpitt** [comment]
Reread the instruction about the input namespace in the assignment. The document is in the TEI namespace, so you need to use the `@xpath-default-namespace` attribute to tell that to the stylesheet.
