### ISSUE TITLE
Orbis Discussion Post

### ISSUE THREAD

**Issue by Jacksweeney1** [obdurodon/dh_course#440]
Orbis at first glance looks amazing, exciting, and well thought out. As a history major, I instantly got excited to see what this site had to offer. To begin, my response to both the research and design aspects of the site (starting with design), the opening pop-up serves to guide and help anyone that enters the site. I found it was both helpful and informative, as it provides information from news about the site to navigating it's various maps. The geospatial network model is designed very well, with an accessible interface chock full of different things one can do when researching. When it comes to research, this site is almost in a league of its own. It is astounding all of the data that is packed into the site, and the amount of work that it must have taken to complete this is gargantuan. Orbis is truly a unique and interesting website, with something for every researcher enthusiastic about the Roman Empire.

**Comment by dap167** [comment]
I agree with your opinion on the opening pop-up as well. It was incredibly well-done. My initial confusion disappeared while I engrossed myself with reading about the site, and my earlier question of "Why did it pop up immediately?" was answered when I finally saw the model.

**Comment by cjw102** [comment]
I thought that the popup was pretty cool, and had a lot of information, but when I first entered the site, I found it to be a bit overwhelming. Also, I did think the popup was kind of a weird way to open the page, and I couldn't immediately find it again after I closed the window. Still had cool information though!

**Comment by Rober-Igtm** [comment]
As a fellow History major, I also really admired the work that went into this. The popup was extremely helpful in introducing the site, and the whole layout was easy to utilize. What I also think needs to be commended is the meticulous way in which the researchers developed calculations for speed, time, and distance across the Empire with various different means of travel at different costs. It's an entirely holistic model of Roman transportation.
