### ISSUE TITLE
XML Prague 2020

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#447]
XML Prague is being live-streamed at <https://www.youtube.com/watch?v=pBDBRTyjArk>, with papers at <https://archive.xmlprague.cz/2020/files/xmlprague-2020-proceedings.pdf>.

**Comment by ebeshero** [comment]
Also, @djbpitt's presentation is here: https://www.youtube.com/watch?v=CYue_wCIJoU Fair warning, if you've not learned XSLT just yet, this might be a bit, er, technical, but I think you'll find the programming applications interesting!
