### ISSUE TITLE
XPath Interactive Practice

### ISSUE THREAD

**Issue by EsRessel** [obdurodon/dh_course#451]
When reading up on XPath for the homework I came across a site with short and interactive practice quizzes. It can be found at [this link](https://www.wwp.northeastern.edu/outreach/seminars/xslt_2012-03/quizzes/index.htm). The site was created by a group of digital humanists called the Women Writers Project. The site has two quizzes for XPath and a few for XSLT, which may come in handy in the future. They are good for getting the basics down and they give you immediate feedback. The site also provides alternative answers if they exist, allowing you to see other ways of getting the same result with a different XPath expression.

**Comment by charlietaylor98** [comment]
This website has a lot of useful information! Thus far in the course we have been focusing on learning programming languages, but the Women Writers Project also has [guidelines](https://www.wwp.northeastern.edu/outreach/seminars/_current/handouts/document_analysis.xhtml) for what to consider when doing document analysis. I know most of us already know what our markup will look like, but this resource might be helpful for anyone feeling stuck deciding what is and isn't important to their documents and research question.
