### ISSUE TITLE
Using CSS in an XSLT Stylesheet

### ISSUE THREAD

**Issue by charlietaylor98** [obdurodon/dh_course#462]
As we discussed on Monday, you style your output html using CSS with the `<style>` element. However, whereas oxygen can check that everything in a .css document is proper CSS syntax, it doesn't do so in a .xsl document. For example, I had written 
`<style>
 ul {backgroun-color: #eeac99; margin-left: 10px}
</style>`
Note that I made a spelling mistake (as I often do) and omitted the "d" in "background". This means that when I generated the HTML, the background remained white. It took me a good minute to figure out why my styling didn't work, whereas in a CSS document I would have known automatically. (Plus, the generation of a lot of CSS rules makes a .xsl document harder to read, at least in my opinion.)

**Comment by pickettj** [comment]
Great point, @charlietaylor98 ! I only use the inline `<style>` element for demos and one-off exceptions.
