### ISSUE TITLE
Github for Johns Hopkins COVID-19 Map

### ISSUE THREAD

**Issue by marionbriley** [obdurodon/dh_course#465]
Hi everyone! 
This is unrelated to actual class material, but I wanted to share. I don't know if anyone has been checking the [Johns Hopkins Coronavirus database of coronavirus cases worldwide](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), but I've found it a pretty useful resource throughout this ordeal. I stumbled upon the [Github project repo](https://github.com/CSSEGISandData/COVID-19) for this database, where the data that goes into the map is stored, and thought you all might be interested in seeing this real life application of what we're learning. I've been exploring it for a while this afternoon, and it's pretty interesting!

**Comment by Rober-Igtm** [comment]
Wow, I'd seen Johns Hopkins' updates on the news, but I didn't know they had all of this data presented in website form. The fact that you can put so much data and computing power of international importance into a single GitHub repo is fascinating!

**Comment by rasaula** [comment]
That's incredibly interesting! I agree with the comments before mine- seeing how Github can hold such important information is really exciting. Just a few months ago, I wouldn't have understood anything about that project repo (or even known what a project repo is), so to see it being applied in such important circumstances is super exciting.
