### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#47]
The sign below, which hangs in the Institute of Czech Literature of the Czech Academy of Sciences, reminds us of the importance of maintaining a proper Git workflow:

![git-fire-drill](https://user-images.githubusercontent.com/6233052/37061023-15434574-2160-11e8-81c2-711b6937a9b4.jpg)

**Comment by JosephDRogers23** [comment]
Was the fire caused by forgetting "git add"? :)
