### ISSUE TITLE
Converting a group of xml files into individual text files using XSLT

### ISSUE THREAD

**Issue by nmcdowell00** [obdurodon/dh_course#472]
This process is doable manually it will just take a while and if there is a way to do this quicker I would be happy to learn about it. It is necessary that each individual xml file be converted to individual text file. I have tried to convert groups of xml files by creating a project within Oxygen and applying transformation scenarios to it but I have only been able to create 1 output text file containing all of the stripped xml. Is there another approach to doing this?

**Comment by djbpitt** [comment]
@nmcdowell00 Great question! See the *batch* subdirectory at <https://github.com/obdurodon/dh_course>
