### ISSUE TITLE
Pushing to Git

### ISSUE THREAD

**Issue by rasaula** [obdurodon/dh_course#476]
I'm currently trying to push one new changed file to our group, but when I check the status before pushing it says I have fifteen changed files, which simply isn't true. On top of that, none of the files include the one I'm actually trying to push. I pulled right before committing any changes, I'm at a bit of a loss as to why this is happening. Any suggestions would be very appreciated!

**Comment by djbpitt** [comment]
@rasaula If you'd like to debug this over Zoom, let me know (respond to this thread, tagging me). I'm free until about 5:30 today.

**Comment by rasaula** [comment]
@djbpitt That would be great. I'm free at 4pm if that works for you!

**Comment by djbpitt** [comment]
@rasaula See you then! Let’s meet at my office-hours Zoom address, the URL for which is listed in an announcement inside CourseWeb.

**Comment by djbpitt** [comment]
@rasaula Closing issue.
