### ISSUE TITLE
Class Discussion 3/12

### ISSUE THREAD

**Issue by brucknerp** [obdurodon/dh_course#50]
Hey, I wanted to ask everyone if they've started to see the outcome of their projects at all. For example, while tagging features all the things that I were looking for came up, and did shift over time, which I thought was cool. I'm excited to see this observation in a hard data form, but what about you guys?

**Comment by JosephDRogers23** [comment]
I'm excited for this as well! It's been awesome to see some trends come to the surface that we saw from other people's projects earlier in the semester. I know that in our markups we've started to see some differences in translation between Spanish and English that we're considering doing some analysis on, which is something that I don't think we were quite expecting out of the project. Even if we don't pursue this angle it's been really interesting to discuss.
