### ISSUE TITLE
XSLT6 question

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#52]
Did anyone have any trouble during the transformation for this homework?  I made sure to do all of the necessary housekeeping like the previous assignments and save the original xml and not just copy/paste.
I didn't get any problems until I did the transformation to HTML and had a number of red lights.  It still generated a readable page though.  Maybe some of these older xml documents don't work perfectly with our current software.

**Comment by djbpitt** [comment]
@mtm80 If the XML is well-formed, you can transform it with XSLT. When you save the HTML output and open it in &lt;oXygen/&gt;, the location of the squiggly red lines and the error messages at the bottom of the screen will explain what’s wrong. Those messages are not always written for humans, but they’re nonetheless the best place to start. The most likely explanation of what you report is that you’ve output invalid HTML with your XSLT. The developer controls the output, so you need to plan what you want your output HTML to look like, and you need to ensure it’s valid, before you generate it.
