### ISSUE TITLE
SVG trouble

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#59]
I'm having trouble with the svg transformation.  It looks solid enough in the browser when I build it in svg but when I do the same in xsl, the browser view gets cut up.  By this, I mean that with just svg, I get the whole view of the chart but when I move it to xsl, I can only see about a quarter of the chart and the rest disappears.  Any ideas?

**Comment by gabikeane** [comment]
Remember the transform attribute on the <g> element. If this doesn't help, make sure you give us an example of code.

**Comment by gabikeane** [comment]
That should say "g element", sorry I'm on mobile and can't edit.

**Comment by djbpitt** [comment]
@mtm80 If I’ve understood correctly that when you write the SVG by hand it looks correct in the browser, but when you generate it with XSLT it doesn’t, the starting point for debugging would be to look at how the hand-wrought code differs from the XSLT output. You can do that manually by opening them both and looking at them, but you may find it easier to use the "XML diff" (that is, show the difference between two XML files) feature of &lt;oXygen/&gt;. See <https://www.oxygenxml.com/xml_editor/xml_diff_and_merge.html#compare-files-tool> for an explanation of how to do that.

**Comment by mtm80** [comment]
I tried the <g> element with negative numbers and all that changed was  which part was visible.  
Full SVG code-

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
    <line x1="40" y1="100" x2="40" y2="500" stroke="black" stroke-width="1"/>
    <line x1="40" y1="500" x2="1500" y2="500" stroke="black" stroke-width="1"/>
    <line x1="40" y1="250" x2="1500"  y2="250" stroke="black" stroke-width="1"/>
    <line x1="40" y1="375" x2="1500"  y2="375" stroke="black" stroke-width="1"/>
    <line x1="40" y1="125" x2="1500"  y2="125" stroke="black" stroke-width="1"/>
    <text x="30" y="500" text-anchor="end">0%</text>
    <text x="30" y="250" text-anchor="end">50%</text>
    <text x="30" y="375" text-anchor="end">25%</text>
    <text x="30" y="125" text-anchor="end">75%</text>
</svg>
Full xsl code-
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/2000/svg"
    exclude-result-prefixes="xs" version="3.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
    <svg>   
        <g transform="translate(-100, -100)">
            <line x1="40" y1="100" x2="40" y2="500" stroke="black" stroke-width="2"/>
        <line x1="40" y1="500" x2="1500" y2="500" stroke="black" stroke-width="2"/>
        <line x1="40" y1="250" x2="1500"  y2="250" stroke="black" stroke-width="2"/>
        <line x1="40" y1="375" x2="1500"  y2="375" stroke="black" stroke-width="2"/>
        <line x1="40" y1="125" x2="1500"  y2="125" stroke="black" stroke-width="2"/>
        <text x="30" y="500" text-anchor="end">0%</text>
        <text x="30" y="250" text-anchor="end">50%</text>
        <text x="30" y="375" text-anchor="end">25%</text>
        <text x="30" y="125" text-anchor="end">75%</text>
 </g>
    </svg>
    </xsl:template>
</xsl:stylesheet>

**Comment by mtm80** [comment]
Full xsl code-
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/2000/svg"
    exclude-result-prefixes="xs" version="3.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
    <svg>   
        <g transform="translate(-100, -100)">
            <line x1="40" y1="100" x2="40" y2="500" stroke="black" stroke-width="2"/>
        <line x1="40" y1="500" x2="1500" y2="500" stroke="black" stroke-width="2"/>
        <line x1="40" y1="250" x2="1500"  y2="250" stroke="black" stroke-width="2"/>
        <line x1="40" y1="375" x2="1500"  y2="375" stroke="black" stroke-width="2"/>
        <line x1="40" y1="125" x2="1500"  y2="125" stroke="black" stroke-width="2"/>
        <text x="30" y="500" text-anchor="end">0%</text>
        <text x="30" y="250" text-anchor="end">50%</text>
        <text x="30" y="375" text-anchor="end">25%</text>
        <text x="30" y="125" text-anchor="end">75%</text>
 </g>
    </svg>
    </xsl:template>
</xsl:stylesheet>

**Comment by mtm80** [comment]
Full xsl code-
> <?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/2000/svg"
    exclude-result-prefixes="xs" version="3.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
    <svg>   
        <g transform="translate(-100, -100)">
            <line x1="40" y1="100" x2="40" y2="500" stroke="black" stroke-width="2"/>
        <line x1="40" y1="500" x2="1500" y2="500" stroke="black" stroke-width="2"/>
        <line x1="40" y1="250" x2="1500"  y2="250" stroke="black" stroke-width="2"/>
        <line x1="40" y1="375" x2="1500"  y2="375" stroke="black" stroke-width="2"/>
        <line x1="40" y1="125" x2="1500"  y2="125" stroke="black" stroke-width="2"/>
        <text x="30" y="500" text-anchor="end">0%</text>
        <text x="30" y="250" text-anchor="end">50%</text>
        <text x="30" y="375" text-anchor="end">25%</text>
        <text x="30" y="125" text-anchor="end">75%</text>
 </g>
    </svg>
    </xsl:template>
</xsl:stylesheet>

**Comment by mtm80** [comment]
I tried the <g> element with negative numbers and all that changed was which part of the chart was visible.    Positive numbers made everything disappear. Github doesn't want to show full code in comments so I'll visit for office hours tomorrow.  Thanks anyway.

**Comment by djbpitt** [comment]
@mtm80 GitHub markdown will show full code if you use the appropriate markdown tagging for code. There are two methods, one for tagging small snippets of inline code and other for tagging code blocks. You can learn how to do this by clicking on the link at the bottom of this page that says “Styling with Markdown is supported” and then, in the “Examples” section, clicking on the “Code” button. Note that the example shows you first the raw markdown and then what it looks like formatted—that is, type the version at the top to see the version below it.

Meanwhile, did you compare the SVG output of your XSLT transformation with the SVG that you wrote by hand, as I suggested above? You closed that issue, but you didn’t respond to it. This is how I would go about debugging this sort of problem: if you can write SVG that does what you want by hand, you need to figure out what you’re doing by hand that works that you’re not doing in your XSLT. Comparing the output is a good way to do that.

**Comment by brucknerp** [comment]
I have a different question--unless I use the same transform values (10 and 110) as in the class exercise, my axes and bars disappear. When I use the same width axes and translation as in class, it shows up, but this makes only a tiny graph. I'm not sure what I'm doing wrong.

When I have this code:
<img width="668" alt="screen shot 2018-03-27 at 19 23 13" src="https://user-images.githubusercontent.com/35678403/38000206-78f1a21a-31f4-11e8-84f7-e172679e56e3.png">

This shows up, like in class:
<img width="693" alt="screen shot 2018-03-27 at 19 23 08" src="https://user-images.githubusercontent.com/35678403/38000196-70e3d476-31f4-11e8-8bd3-34a4a1f160b5.png">

Then if I change the transformation values:
<img width="587" alt="screen shot 2018-03-27 at 19 23 41" src="https://user-images.githubusercontent.com/35678403/38000219-8d3936a2-31f4-11e8-8e86-c6c3950d6c7c.png">

I get nothing.

Then if I also change the axes values:
<img width="584" alt="screen shot 2018-03-27 at 19 24 00" src="https://user-images.githubusercontent.com/35678403/38000227-96b8cd96-31f4-11e8-87a7-28918d81f095.png">

I get a sad line:
<img width="807" alt="screen shot 2018-03-27 at 19 23 57" src="https://user-images.githubusercontent.com/35678403/38000235-9c952264-31f4-11e8-9e44-cd43bb5a0658.png">

Any thoughts???

**Comment by djbpitt** [comment]
@brucknerp This is typically a rendering problem; your image is there, but it’s getting cropped. To fix it, first try adding `@width` and `@height` attributes to your `<svg>` root element, with values set to "100%", e.g.:
```xml
<svg xmlns="http://www.w3.org/2000/svg" height="100%" width="100%">
```
If that doesn’t help, try also adding a `@viewBox` attribute. You can read about the `@viewBox` attribute at <http://www.sarasoueidan.com/blog/svg-coordinate-systems/> (this is one of the clearest SVG tutorials I’ve seen, and it’s worth reading even if you aren’t having rendering problems). Try a value like:
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 650 350" height="100%" width="100%">
```
where the first two values of the `@viewBox` attribute are both `0`, the third is the width of your image (the length of your X axis, plus a bit extra), and the fourth is the height (the length of the Y axis, plus a bit extra). You may need to fiddle with the numbers, but that should save you from the Sad Line effect. If you still can’t get it to work, create a GitHub repo, push your XSLT, post the repo URL here, and we’ll take a look.
