### ISSUE TITLE
Influence in Russian Poetry 

### ISSUE THREAD

**Issue by richiebful** [obdurodon/dh_course#6]
Exploring Russian-language poetry during the Silver Age (roughly 1890-1922), this project aspires to confirm and discover linkages between different poets' styles. In general, we hope to mark up the work of at least ten poets from the period, taking from each a diverse sample size of at least ten poems from each across the given time period. For example, in the case of Anna Akhmatova, I might take 3 poems from _Vecher_, 3 from _Chetki_, 2 from _Belaya Staya_, 2 from _Podorozhnik_, also including unpublished poems as well, if available. Then we will markup the chosen corpus with information on the meter, rhythm and rhyme. I would prefer to generalize this approach into a computer assisted analysis, marking up stressed syllables, different rhyme schemes, and word recurrence without manual effort, which will allow us to scale the size of the corpus quickly. Then we will use the given data to produce a "fingerprint" for a given author: the words they use more common than other poets, the stress patterns that set them apart, and display this information to the user using JavaScript D3. Finally we will use a clustering algorithm to physically show what poets likely influenced one another, based on their similar styles.
## Questions ##
Who ends up being grouped by style and word choice? Does this correspond with traditional assumptions about the poets' influences? What makes an individual poet special? Does that correspond with contemporary and present-day criticism?

## Potential team members: ##
- @ianloughney
- @mtm80
- Other Russian-speakers

**Comment by djbpitt** [comment]
@richiebful This is a particular interest of mine (see <http://poetry.obdurodon.org>), and there’s plenty of work still to be done in this area, so I’d be eager to see this proposal go forward. But it’s _your_ project that we’re talking about at the moment, so you should make whatever decision you consider most rewarding. But whatever you decide, you may want to come to [a lecture by Dr. Elise Thorsen](https://www.ucis.pitt.edu/crees/events/using-algorithms-read-pushkins-poetry), my collaborator on my Russian poetry project (and an alumna of our course), on Friday, February 9, 2018 at 2:30pm in 4217 Posvar Hall.
