### ISSUE TITLE
Bars in the Sky?

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#61]
Hey guys, I'm 90% done with my homework, save one annoying detail: when I apply the templates for the data itself, all my bars are floating above the chart, apparently starting at the y-value I gave for the top of the y-axis. I've tried checking if it's a negative number issue but it doesn't seem to be so; any help positioning just the `<xsl:apply-templates/>` inside the g (or otherwise)?

**Comment by djbpitt** [comment]
@Idi0teque Normally we put the entire graph inside a `<g>` element, draw it all in the upper right quadrant, and move it all into the lower right quadrant. But aside from that: what do you see when you look at the angle-bracketed output? Are the positioning values what you expect?

**Comment by Idi0teque** [comment]
Discovered my issue: was not subtracting 200 from the y value of my bar chart template. Will close.
