### ISSUE TITLE
Representing Data

### ISSUE THREAD

**Issue by danakaufhold** [obdurodon/dh_course#63]
Hi all!

So Emily and I are hard at work on our project. This week we discussed what sort of graphical representation of data we plan on including in our website. The only problem is that a lot of our data leans towards the more qualitative side. I was wondering if anyone else's project fits this, and if anyone has any ideas they're planning on using that they'd feel comfortable sharing. We do want to make sure that we have some graphics just so that visitors to our site aren't completely inundated with a wall of text, but we also want those graphics to represent meaningful data.

Thanks in advance!!

**Comment by JosephDRogers23** [comment]
While our project's data has plenty of quantitative aspects that we're trying to take advantage of, we're also trying to do geographic representations on our site and have visualizations of other aspects of our project. Could you find a way to visualize common words, possibly, or have a fantasy map displayed on your site?
