### ISSUE TITLE
eXist-db bug

### ISSUE THREAD

**Issue by djbpitt** [obdurodon/dh_course#64]
In class we ran the following code:
```xquery
xquery version "3.0";
declare namespace tei="http://www.tei-c.org/ns/1.0";
doc('/db/apps/shakespeare/data/ham.xml')//tei:body/tei:div/count(tei:div)
```
and it returned a single integer value of `20`, although we expected it to return five values, one for each act. The reason we expect five values is that each path step begins at the preceding path step, so the counting should happen separately for each act. It turns out that this is a bug in eXist 2.2. which is what we’re running on Obdurodon. When we try it in a more recent version of eXist, we get the results we expect. If you download and install your own copy of eXist, which we encourage you to do, you’ll get version 4.0, which does not have this bug.

**Comment by ebeshero** [comment]
I can confirm that on the [newtfire eXist-db](http://newtfire.org:8338) running a later version of eXist for the Greensburg campus course, this outputs what we'd expect: the number of child `<div>` elements inside each act: 
5
2
2
3
4
4
7
5
2
