### ISSUE TITLE
eXist won't launch?

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#66]
Hey guys, just a little confused and looking for help.

I installed eXist on my home PC via the .jar file on the download page. Chrome initially didn't want me to do so, but I ignored it. Now, however, clicking the "launch" icon results in... nothing happening at all. I can always use the online version of the software, but does anyone know if something obviously wrong is happening here/have the same issue?

Thanks guys!

**Comment by djbpitt** [comment]
@Idi0teque Are you sure that nothing is happening at all? What happens when you launch eXist and then point your browser at http://localhost:8080?

**Comment by Idi0teque** [comment]
Literally nothing; no task appears in task manager, no applications launching, it's as if I just clicked on my desktop.

**Comment by djbpitt** [comment]
@Idi0teque What do you see in the browser window? If eXist isn't running, you should see an error message about not being able to connect. If it is running, you should see the eXist dashboard. I don't know that it means to see "literally nothing" in your browser window?

**Comment by Idi0teque** [comment]
Ah, sorry; I see a "the site can't be reached" error.

**Comment by djbpitt** [comment]
@Idi0teque Okay, that means that eXist failed to launch. Are you on a laptop (that is, can you bring your machine with you tomorrow, so that we can trouble-shoot it with you)?

**Comment by Idi0teque** [comment]
Unfortunately no, I'm on my desktop. I'll install it on my laptop, though, and see if I can replicate/solve the problem there!

**Comment by djbpitt** [comment]
@Idi0teque Let us know what happens when you try the installation on your laptop. Are you running the same version of Windows on both? And the same version of Java?
