### ISSUE TITLE
Religious References in Modest Mouse Discography

### ISSUE THREAD

**Issue by JosephDRogers23** [obdurodon/dh_course#7]
# Religious References in Modest Mouse Discography

## __Text__
The text of this project will come from the lyrics of all songs from Modest Mouse albums, from 1992 to the present. If lyrics cannot be found to the songs from all albums, emphasis will be placed on taking songs from albums spanning as much of the lifespan of the group as possible (meaning that equal amounts of songs will be used from the early and later parts of the 1990s, 2000s, and 2010s). Lyrics will be taken from materials by Modest Mouse when possible, and from reputable internet sources when direct information from Modest Mouse is not available. 

## __Approach__
Document analysis will be performed on these songs lyrics to find all references to religious stories from the Christian Bible, and both numeric amounts of references per album and decade as well as classifications (by moral message) of each story referenced will be noted. Religious stories will be classified into separate groups and moral messages of each story referenced will be broadly categorized and analyzed as well. 

## __Questions__
Isaac Brock, the lead singer and songwriter of Modest Mouse, is a self-professed atheist and frequent criticizer of religion, yet makes dozens of references to Christian stories across multiple albums. This project will attempt to explore two main questions: How has the amount of religious references in Modest Mouse's songs increased or decreased over time, and is there an overall pattern of moral messages being expressed in these references? The project will explore these questions by counting the number of references and charting how these numbers changed over the course of each album from Modest Mouse. It will then analyze the individual stories and characters referenced in the songs and find if a broad pattern of moral messages has been emphasized over the course of Brock's career. 

# __Participants__
Any person with a vested interest or knowledge of songs and lyrics by Modest Mouse are welcome to join.

**Comment by gabikeane** [comment]
ooh, very cool.  I'd love to contrast this to Sufjan Stevens' discography, a contemporary of Brock with a very Christian background.

**Comment by JosephDRogers23** [comment]
If anyone has interest on doing this one, let me know!

**Comment by djbpitt** [comment]
I’m sorry to have to be the Annoying Copyright Nag, but song lyrics are protected by copyright, and their republication on the Internet without permission has led to lawsuits (see, for example, the suite against Rap Genius described at <https://www.nytimes.com/2014/05/07/business/media/rap-genius-website-agrees-to-license-with-music-publishers.html>). Some artists grant permission (on their own sites) for the republication of lyrics, so it isn’t the case that all contemporary music is out of bounds, but you’ll need to look into what the copyright holders do and do not permit in individual cases.
