### ISSUE TITLE
XQuery Question (Again)

### ISSUE THREAD

**Issue by Idi0teque** [obdurodon/dh_course#71]
Hey all, hope your evening's going well,

In my XQuery assignment, I'm successfully able to return cells with distinct act names, scene names, and speakers. The problem is, they're one cell each, with cells containing things like "Act1Act2Act3Act4Act5." How can I get the <td> elements to wrap around the individual names, rather than all of them combined? (This might overlap into XPath, not sure.) Thanks!

**Comment by gmd29** [comment]
I think you might be missing a "for" statement.

**Comment by Idi0teque** [comment]
Okay, change of tactic since I was able to find ways around that: I still have single <td> cells that contain "Scene 1Scene 2Scene 3..." and I'm trying to get those into their own cells using nested FLWOR; but my current tactic:
```
{for $scene in $act
            let $scenes :=  $act//tei:div
            let $sceneName := data($scenes/tei:head)
            return <td>{$sceneName}</td>}
```
is just getting the above result. Is there something obviously wrong here? This worked for the `$acts`...

**Comment by djbpitt** [comment]
One step at a time. You’re defining a bunch of variables before you return anything, which makes it hard to find where you’re going astray. Define one variable at a time, figure out what the value should be before you return it, then return it and compare the result to your prediction. If the value isn't what you expected, explain to your rubber duck, step by step, what you think the result should be and why. Your code always gives you exactly what you ask for, so if it isn't what you want, it means that you weren’t asking for what you thought you were asking for. And if the first variable value is wrong, everything that depends on it will be wrong, and similarly for each of the others, so there’s no point in writing the next line until the last line is doing what you want. 

Assuming the value of `$act` in your example is correct, start with
```xquery
for $scene in $act
return $scene
```
If you like the results, move on to the next variable:
```xquery
for $scene in $act
let $scenes := $act//tei:div
return $scenes
```
etc.

**Comment by rmb165** [comment]
In my XQuery, I'm having a difficult time with the nested for loops, I tried to set it up the same way as in the XQuery homework two, but I keep getting different error messages.
