### ISSUE TITLE
Xquery problem

### ISSUE THREAD

**Issue by mtm80** [obdurodon/dh_course#72]
I'm using the following at the beginning of the xquery
xquery version "3.0";
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $play := doc('/db/apps/shakespeare/data/ham.xml');
and I get the right play but when I look for portions of the play I get totally different documents.
Example
<tr>
                {let $act := //tei:body/tei:head[1]
                   return <td>{$act}</td>}
Any ideas?

**Comment by ebeshero** [comment]
Why aren't you using the $play variable you defined that isolates Hamlet? Also, take a look at your syntax on the line in which you're defining $act: how does it compare with syntax you've written or seen elsewhere?

**Comment by djbpitt** [comment]
@mtm80 Your experience of retrieving data from the wrong plays illustrates something we’ve said frequently in class: in XQuery, a path expression that begins with a double slash looks in the entire eXist database, not only at all of the Shakespeare plays, but at all documents in all collections in all projects. Your definition of `$act` matches every first `<head>` child of every `<body>` in every TEI document in the entire database, and it has no way of knowing that you’re interested in _Hamlet_. For that reason, it is always a mistake to begin a path expression in XQuery with a double slash. It’s a valid path expression, so it won’t raise an error message, but it will never be what you want. If you want data only from _Hamlet_, you need to tell your path expression to look only in _Hamlet_.
