### ISSUE TITLE
Most-Used Tool So Far?

### ISSUE THREAD

**Issue by danakaufhold** [obdurodon/dh_course#75]
I know that we are all using all of the different resources we've learned about in the course, but I was wondering if anyone had a tool that they've found their project relying quite heavily on. It might be interesting to compare which projects use which resources, and what kind of data those particular projects are focused on. If no one has seen an emergence in one specific tool, then I suppose you could just comment which one you think has been the most useful to you so far!

**Comment by djbpitt** [comment]
@danakaufhold Wanna start off the discussion by telling us what _you’ve_ found most useful?
