### ISSUE TITLE
Use of rhetoric in Magical Realism

### ISSUE THREAD

**Issue by rmb165** [obdurodon/dh_course#8]
Use of rhetoric in Magical Realism

For my research project I would like to analyze the use of rhetoric by magical realist authors   ##to discreetly criticize the government and society. I plan on using excerpts from Gabriel García Márquez’s “One Hundred Years of Solitude”, "El ahogado más hermoso del mundo", and "La siesta del martes", Jorge Luis Borges’s “El Sur”, Julio Cortázar’s "La noche boca arriba", and Carlos Fuentes’s “Chac Mool” to name a few of the texts I would like to analyze. My research question will be “How do magic realism authors use their stories to make a critique of the government and society without putting themselves in danger of forced disappearances or exile?” I will explore this by looking for references to historical events in the authors’ short stories. I will also look for characteristics that may be satirical of political figures or problems that the authors see in society. For example, in “One Hundred Years of Solitude”, Márquez talks about a banana massacre which is suspiciously similar to the one the occurred in Colombia during the lives of his parents and grandparents. An example of a satirical characteristic is the character Dahlmann in Borges’s “El Sur” who thinks he is the same as his distant gaucho ancestors, even though he is of mostly German descent, which Borges does as a jab at Argentinians denying their European heritage to feel like they are a part of the nationalist Argentinian movement. I would like to explore other examples of how each text does this, if the texts do it, and what critiques the author might be trying to make. I would also like to look at if the authors have any positive critiques of the government and society, which is often not mentioned when analyzing these texts.  I will explore more authors and texts, focusing on Latin American authors, and may even extend my project to writing styles other than magic realism, such as poetry or other narratives.

**Comment by zme1** [comment]
@rmb165 Only open issues will appear on the Issues board in our repository. Once it's closed, it's archived. We will reopen this until project teams are selected so everyone has a chance to read it.

**Comment by rmb165** [comment]
Thank you @zme1 , also, I don't know how to label this as my project proposal

**Comment by zme1** [comment]
@rmb165 On your desktop window, there is a menu bar on the right-hand side with different modifications you can make to the Issue. Click the gear icon next to "Labels" and select the one that says "project proposal."

**Comment by Idi0teque** [comment]
I absolutely adore Borges' writings and love Magical Realism! If you need a group member and no one signed up for mine, count me interested!

**Comment by JosephDRogers23** [comment]
This is interesting to me as well! Very cool!

**Comment by rmb165** [comment]
I'd love to work together! @Idi0teque If you would like to work together too, let me know! @JosephDRogers23

**Comment by djbpitt** [comment]
@rmb165 @Idi0teque @JosephDRogers23 @zme1 @gabikeane Working with Borges is tricky because his writings are under copyright and his estate is especially litigious (see <https://sevencircumstances.com/2017/01/23/fan-fiction-versus-copyright-the-aleph/>). But, happily, the University of Pittsburgh is home to Professor Dan Balderston’s [Borges center](http://www.borges.pitt.edu/), and they might be able to help you identify a Borges-related project that would not entail copyright violation. Professor Balderston has some experience in DH methods, so if you decide to reach out to him to discuss your interests, mention our course. If you decide you’d like to do that, though, please try to do it before Friday morning, so that we can proceed with forming our project teams on schedule.

**Comment by rmb165** [comment]
@djbpitt  @Idi0teque @JosephDRogers23 @zme1 @gabikeane Thank you for your advice on this project,
I just reached out to Professor Balderston and will hopefully have a response by Friday morning.
